using System;
using System.Collections;
using System.Collections.Generic;
using Memori.Audio;
using Memori.Utilities;
using Memori.UI;
using TMPro;
using UnityEngine;
using UnityEngine.EventSystems;
using UnityEngine.InputSystem;
using UnityEngine.UI;

namespace TJ
{
    /// <summary>
    /// One standing card on a pick-one panel (Prestige III traits, Ordeals, Treasure), generated by ChoicePanelBuilder.
    /// The panel fills it and listens to Chosen; the card only shows what it is given.
    /// </summary>
    public class ChoiceCardView : MonoBehaviour, IPointerEnterHandler, IPointerExitHandler, ISelectHandler, IDeselectHandler, IPointerDownHandler, IPointerUpHandler
    {
        public enum NoteKind { Warning, Map, Gold }
        public enum GroupMotion { Idle, Hovered, Neighbour, Pressed }

        [SerializeField] private Button button;
        [SerializeField] private LayoutElement layoutElement;
        // Enter, pick and pop animate this wrapper, so the root keeps its layout slot and hit box.
        [SerializeField] private RectTransform pop;
        [SerializeField] private CanvasGroup popGroup;
        [SerializeField] private RectTransform lift;
        [SerializeField] private Image hoverHalo;
        [SerializeField] private Image hoverTint;
        [SerializeField] private Image pickedGlow;
        [SerializeField] private GameObject band;
        [SerializeField] private Image bandFill;
        [Tooltip("The centre glow under the frame; the fill is its left half, this the right.")]
        [SerializeField] private GameObject bandGlow;
        [SerializeField] private Image bandFillRight;
        [SerializeField] private TMP_Text bandText;
        [SerializeField] private GameObject newChip;
        [SerializeField] private HorizontalOrVerticalLayoutGroup contentLayout;
        [SerializeField] private Image icon;
        [SerializeField] private TMP_Text nameText;
        [SerializeField] private TMP_Text description;
        [SerializeField] private GameObject notes;
        [SerializeField] private Image[] noteIcons;
        [SerializeField] private TMP_Text[] noteTexts;
        [SerializeField] private TMP_Text footer;
        [SerializeField] private GameObject done;
        [SerializeField] private TMP_Text doneText;

        #region Look
        [SerializeField] private Color nameColour = new(0.914f, 0.753f, 0.416f, 1f);
        [SerializeField] private Color nameHoverColour = new(0.949f, 0.808f, 0.486f, 1f);
        [SerializeField] private Color namePickedColour = new(1f, 0.890f, 0.639f, 1f);
        [SerializeField] private Color footerColour = new(0.549f, 0.604f, 0.635f, 1f);
        [SerializeField] private Color footerHoverColour = new(0.620f, 0.847f, 1f, 1f);
        [SerializeField] private Color warningColour = new(0.890f, 0.412f, 0.369f, 1f);
        [SerializeField] private Color mapColour = new(0.890f, 0.733f, 0.443f, 1f);
        [SerializeField] private Color coinColour = new(0.890f, 0.733f, 0.443f, 1f);
        [SerializeField] private Sprite warningIcon;
        [SerializeField] private Sprite mapIcon;
        [SerializeField] private Sprite goldIcon;
        [SerializeField] private float contentTop = 40f;
        [SerializeField] private float contentTopWithBand = 76f;
        #endregion

        #region Motion
        [SerializeField] private float liftHeight = 12f;
        [SerializeField] private float liftSeconds = 0.1f;
        [SerializeField] private float enterRise = 30f;
        [SerializeField] private float enterSeconds = 0.22f;
        [SerializeField] private string popSfx = "upgrade-unlock";
        [SerializeField] private float punchScale = 1.06f;
        [SerializeField] private float punchSeconds = 0.07f;
        [SerializeField] private float vanishScale = 0.9f;
        [SerializeField] private float vanishSeconds = 0.16f;
        [SerializeField] private float dealStartScale = 0.85f;
        [SerializeField] private float dealPeakScale = 1.06f;
        [SerializeField] private float dealSeconds = 0.3f;
        #endregion

        #region Group motion fields
        // The recruit cards' motion (RecruitCard): the hovered card grows and lifts, the rest shrink, idle cards breathe.
        const float HoverScale = 1.15f, NeighbourScale = 0.92f, PressedScale = 0.9f;
        const float HoverLift = 20f;
        const float HoverInDuration = 0.1f, HoverOutDuration = 0.08f, PressDuration = 0.03f;
        const float BreathAmplitude = 4f, BreathPeriod = 1.8f, BreathStagger = 0.3f;
        // Inset of the hit box from the card edge, so a shrinking neighbour cannot flicker the hover.
        const float HitBoxInset = 20f;
        private bool groupHover;
        private bool breathes = true;
        private bool movesOnHover = true;
        private int groupIndex;
        private GroupMotion groupMotion = GroupMotion.Idle;
        private bool motionActive;
        private bool motionSettled = true;
        private float motionStartTime, motionDuration, startScale, targetScale, startY, targetY;
        private float breathClock;
        #endregion

        public event Action<ChoiceCardView> Chosen;
        /// <summary>Group hover only: raised when the pointer or keyboard focus arrives (true) or leaves (false).</summary>
        public event Action<ChoiceCardView, bool> HoverChanged;
        /// <summary>Group hover only: raised when the card has risen in and can take its place in the hover.</summary>
        public event Action<ChoiceCardView> MotionStarted;
        public Button Button => button;
        /// <summary>True once the enter animation has finished.</summary>
        public bool Landed { get; private set; } = true;

        private bool hovered;
        private bool focused;
        private bool locked;
        private bool blocked;
        private bool armed;
        private float armedTime;
        private float pressTime;
        private Coroutine liftRoutine;
        private Coroutine popRoutine;

        private void Awake()
        {
            button.onClick.AddListener(Click);
            ShowHighlight(false, true);
            pickedGlow.enabled = false;
            done.SetActive(false);
            if (newChip != null) newChip.SetActive(false);
        }

        #region Content
        public void SetSize(Vector2 size)
        {
            layoutElement.minWidth = layoutElement.preferredWidth = size.x;
            layoutElement.minHeight = layoutElement.preferredHeight = size.y;
            ((RectTransform)transform).sizeDelta = size;
        }

        /// <summary>A null or empty band label hides the group band.</summary>
        public void Load(Sprite iconSprite, string title, string bandLabel, Color bandColour, string descriptionText, string footerLabel, string doneLabel)
        {
            icon.sprite = iconSprite;
            icon.enabled = iconSprite != null;
            nameText.text = title;
            bool hasBand = !string.IsNullOrEmpty(bandLabel);
            band.SetActive(hasBand);
            if (bandGlow != null) bandGlow.SetActive(hasBand);
            if (hasBand)
            {
                bandText.text = bandLabel;
                bandText.color = bandColour;
                bandFill.color = new Color(bandColour.r, bandColour.g, bandColour.b, bandFill.color.a);
                if (bandFillRight != null) bandFillRight.color = bandFill.color;
            }
            // A new RectOffset, because editing the old one in place does not mark the layout for a rebuild.
            RectOffset padding = contentLayout.padding;
            contentLayout.padding = new RectOffset(padding.left, padding.right, Mathf.RoundToInt(hasBand ? contentTopWithBand : contentTop), padding.bottom);
            KeywordText.Apply(description, descriptionText);
            footer.text = footerLabel;
            doneText.text = doneLabel;
            blocked = false;
            SetNotes(null);
        }

        public void SetNew(bool isNew)
        {
            if (newChip != null) newChip.SetActive(isNew);
        }

        /// <summary>Shows a full-colour item icon (gear, consumables) in place of a gold-tinted glyph.</summary>
        public void ShowArtIcon(float size)
        {
            icon.color = Color.white;
            icon.rectTransform.sizeDelta = new Vector2(size, size);
        }

        /// <summary>The footer says why the card cannot be taken right now. The card still hovers and still raises Chosen.</summary>
        private Coroutine denyShake;

        // A refused pick shakes the card face; the error notification already plays the sound.
        public void Deny()
        {
            if (!isActiveAndEnabled || button == null) return;
            if (denyShake != null) StopCoroutine(denyShake);
            denyShake = StartCoroutine(UIJuice.Shake(button.transform as RectTransform));
        }

        public void SetBlocked(string reason)
        {
            blocked = true;
            footer.text = reason;
            ShowHighlight(hovered || focused, true);
        }

        /// <summary>Switches the card to the recruit cards' group motion. The panel drives it through SetGroupMotion.</summary>
        public void UseGroupHover(int index, bool breathe = true, bool moveOnHover = true)
        {
            groupHover = true;
            breathes = breathe;
            movesOnHover = moveOnHover;
            groupIndex = index;
            Graphic hitBox = button.targetGraphic;
            if (hitBox != null) hitBox.raycastPadding = Vector4.one * HitBoxInset;
        }

        public void SetNotes(IReadOnlyList<(NoteKind kind, string text)> lines)
        {
            int count = lines == null ? 0 : Mathf.Min(lines.Count, noteTexts.Length);
            notes.SetActive(count > 0);
            for (int i = 0; i < noteTexts.Length; i++)
            {
                bool shown = i < count;
                noteTexts[i].transform.parent.gameObject.SetActive(shown);
                if (!shown) continue;
                Color colour = lines[i].kind == NoteKind.Map ? mapColour : ColorVision.Bad(warningColour);
                noteTexts[i].text = lines[i].text;
                noteTexts[i].color = colour;
                noteIcons[i].sprite = lines[i].kind switch
                {
                    NoteKind.Map => mapIcon,
                    NoteKind.Gold => goldIcon,
                    _ => warningIcon,
                };
                // The icons are white art: the coin takes the gold amount colour, the others their line's colour.
                noteIcons[i].color = lines[i].kind == NoteKind.Gold ? coinColour : colour;
            }
        }
        #endregion

        #region States
        // A click only counts once the panel has armed the card, and a mouse press held from before arming never counts.
        private void Click()
        {
            if (locked || !armed) return;
            if (PointerUsedLast() && pressTime < armedTime) return;
            Chosen?.Invoke(this);
        }

        /// <summary>Lets the card take clicks. The panel calls it once every card has landed.</summary>
        public void Arm()
        {
            armed = true;
            armedTime = Time.unscaledTime;
        }

        /// <summary>Stops hover and clicks once any card on the panel is picked.</summary>
        public void Lock()
        {
            locked = true;
            button.interactable = false;
            FreezeGroupMotion();
            ShowHighlight(false, false);
        }

        public void ShowPicked()
        {
            Lock();
            pickedGlow.enabled = true;
            nameText.color = namePickedColour;
            footer.gameObject.SetActive(false);
            done.SetActive(true);
            // The pick punches in place, on the click; nothing flies.
            if (isActiveAndEnabled) StartCoroutine(UIJuice.Punch(pop, 1.06f));
        }

        /// <summary>Punches, then shrinks and fades out. The root keeps its layout slot, so the picked card never moves.</summary>
        public void PopAway(bool withSound)
        {
            Lock();
            if (popRoutine != null) StopCoroutine(popRoutine);
            if (!isActiveAndEnabled)
            {
                pop.gameObject.SetActive(false);
                return;
            }
            popRoutine = StartCoroutine(Vanish(withSound));
        }

        /// <summary>Hides the card until PlayEnter shows it.</summary>
        public void Conceal()
        {
            if (popRoutine != null) StopCoroutine(popRoutine);
            popRoutine = null;
            pop.gameObject.SetActive(true);
            pop.localScale = Vector3.one;
            pop.anchoredPosition = Vector2.zero;
            popGroup.alpha = 0f;
            Landed = false;
        }

        /// <summary>Rises in after the delay, or with deal set, pops in with a card sound.</summary>
        public void PlayEnter(float delay, bool deal = false)
        {
            Conceal();
            if (!deal) pop.anchoredPosition = new Vector2(0f, -enterRise);
            if (!isActiveAndEnabled)
            {
                popGroup.alpha = 1f;
                pop.anchoredPosition = Vector2.zero;
                Landed = true;
                StartGroupMotion();
                return;
            }
            popRoutine = StartCoroutine(deal ? Deal(delay) : Enter(delay));
        }

        private IEnumerator Enter(float delay)
        {
            for (float t = 0f; t < delay; t += Time.unscaledDeltaTime) yield return null;
            for (float t = 0f; t < enterSeconds; t += Time.unscaledDeltaTime)
            {
                float k = 1f - Mathf.Pow(1f - t / enterSeconds, 3f);
                popGroup.alpha = k;
                pop.anchoredPosition = new Vector2(0f, Mathf.Lerp(-enterRise, 0f, k));
                yield return null;
            }
            FinishEnter();
        }

        // Grows past full size in the first 60%, then settles back; fully opaque by the halfway mark.
        private IEnumerator Deal(float delay)
        {
            for (float t = 0f; t < delay; t += Time.unscaledDeltaTime) yield return null;
            IAudioRequester.Instance.PlaySFX(SFXData.CardDraw);
            pop.localScale = Vector3.one * dealStartScale;
            for (float t = 0f; t < dealSeconds; t += Time.unscaledDeltaTime)
            {
                float p = t / dealSeconds;
                popGroup.alpha = Mathf.Clamp01(p * 2f);
                float scale = p < 0.6f
                    ? Mathf.Lerp(dealStartScale, dealPeakScale, 1f - Mathf.Pow(1f - p / 0.6f, 2f))
                    : Mathf.Lerp(dealPeakScale, 1f, Mathf.SmoothStep(0f, 1f, (p - 0.6f) / 0.4f));
                pop.localScale = Vector3.one * scale;
                yield return null;
            }
            FinishEnter();
        }

        private void FinishEnter()
        {
            popGroup.alpha = 1f;
            pop.localScale = Vector3.one;
            pop.anchoredPosition = Vector2.zero;
            popRoutine = null;
            Landed = true;
            StartGroupMotion();
        }

        private IEnumerator Vanish(bool withSound)
        {
            if (withSound) IAudioRequester.Instance.PlaySFX(popSfx);
            for (float t = 0f; t < punchSeconds; t += Time.unscaledDeltaTime)
            {
                pop.localScale = Vector3.one * Mathf.Lerp(1f, punchScale, t / punchSeconds);
                yield return null;
            }
            for (float t = 0f; t < vanishSeconds; t += Time.unscaledDeltaTime)
            {
                float k = t / vanishSeconds;
                pop.localScale = Vector3.one * Mathf.Lerp(punchScale, vanishScale, k * k);
                popGroup.alpha = 1f - k;
                yield return null;
            }
            pop.gameObject.SetActive(false);
            popRoutine = null;
        }
        #endregion

        #region Hover and focus
        public void OnPointerEnter(PointerEventData eventData)
        {
            if (locked) return;
            hovered = true;
            // A hidden card still has its hit box, so it stays quiet until it shows.
            if (popGroup.alpha > 0.5f) IAudioRequester.Instance.PlaySFX(SFXData.LightMouseOver);
            ShowHighlight(true, false);
            if (groupHover) HoverChanged?.Invoke(this, true);
        }

        public void OnPointerExit(PointerEventData eventData)
        {
            hovered = false;
            ShowHighlight(focused, false);
            if (groupHover && !focused && !locked) HoverChanged?.Invoke(this, false);
        }

        public void OnSelect(BaseEventData eventData)
        {
            if (locked || eventData is PointerEventData || PointerUsedLast()) return;
            focused = true;
            ShowHighlight(true, false);
            if (groupHover) HoverChanged?.Invoke(this, true);
        }

        public void OnDeselect(BaseEventData eventData)
        {
            focused = false;
            ShowHighlight(hovered, false);
            if (groupHover && !hovered && !locked) HoverChanged?.Invoke(this, false);
        }

        public void OnPointerDown(PointerEventData eventData)
        {
            if (eventData.button != PointerEventData.InputButton.Left) return;
            pressTime = Time.unscaledTime;
            if (!groupHover || locked || !armed) return;
            SetGroupMotion(GroupMotion.Pressed);
        }

        public void OnPointerUp(PointerEventData eventData)
        {
            // Leaving the card while pressed already fired OnPointerExit, so Pressed here means still over it.
            if (!groupHover || groupMotion != GroupMotion.Pressed) return;
            SetGroupMotion(GroupMotion.Hovered);
        }

        // A mouse click also selects the card; the focus ring is for keyboard and controller players.
        public static bool PointerUsedLast()
        {
            Mouse mouse = Mouse.current;
            if (mouse == null) return false;
            double other = 0;
            if (Keyboard.current != null) other = Math.Max(other, Keyboard.current.lastUpdateTime);
            if (Gamepad.current != null) other = Math.Max(other, Gamepad.current.lastUpdateTime);
            return mouse.lastUpdateTime > other;
        }

        private void ShowHighlight(bool on, bool instant)
        {
            on &= !locked;
            hoverHalo.enabled = on;
            hoverTint.enabled = on;
            if (!pickedGlow.enabled) nameText.color = on ? nameHoverColour : nameColour;
            footer.color = blocked ? ColorVision.Bad(warningColour) : on ? footerHoverColour : footerColour;
            // Group motion owns the lift wrapper's scale and height.
            if (groupHover) return;
            float target = on ? liftHeight : 0f;
            if (liftRoutine != null) StopCoroutine(liftRoutine);
            liftRoutine = null;
            if (instant || !isActiveAndEnabled) lift.anchoredPosition = new Vector2(0f, target);
            else liftRoutine = StartCoroutine(Lift(target));
        }

        private IEnumerator Lift(float target)
        {
            float start = lift.anchoredPosition.y;
            for (float t = 0f; t < liftSeconds; t += Time.unscaledDeltaTime)
            {
                lift.anchoredPosition = new Vector2(0f, Mathf.Lerp(start, target, t / liftSeconds));
                yield return null;
            }
            lift.anchoredPosition = new Vector2(0f, target);
            liftRoutine = null;
        }
        #endregion

        #region Group motion
        // Starts once the card has risen in, so the breath never fights the enter animation.
        private void StartGroupMotion()
        {
            if (!groupHover || locked) return;
            motionActive = true;
            motionSettled = true;
            groupMotion = GroupMotion.Idle;
            breathClock = -groupIndex * BreathStagger;
            // Cards rise in one at a time; a late card has to join a hover that is already underway.
            if (hovered || focused) HoverChanged?.Invoke(this, true);
            else MotionStarted?.Invoke(this);
        }

        // Holds the card where the hover left it, so the picked card does not jump when the panel locks.
        private void FreezeGroupMotion()
        {
            if (!motionActive) return;
            motionActive = false;
            if (motionSettled) return;
            lift.localScale = Vector3.one * targetScale;
            SetLiftY(targetY);
        }

        public void SetGroupMotion(GroupMotion state)
        {
            if (!motionActive || groupMotion == state) return;
            groupMotion = state;
            startScale = lift.localScale.x;
            startY = lift.anchoredPosition.y;
            switch (state)
            {
                case GroupMotion.Hovered:
                    targetScale = movesOnHover ? HoverScale : 1f; targetY = movesOnHover ? HoverLift : 0f; motionDuration = HoverInDuration; break;
                case GroupMotion.Neighbour:
                    targetScale = NeighbourScale; targetY = 0f; motionDuration = HoverInDuration; break;
                case GroupMotion.Pressed:
                    targetScale = PressedScale; targetY = 0f; motionDuration = PressDuration; break;
                default:
                    // Breath restarts from the bottom, each card waiting its stagger before rising.
                    targetScale = 1f; targetY = breathes ? -BreathAmplitude : 0f; motionDuration = HoverOutDuration;
                    breathClock = -groupIndex * BreathStagger; break;
            }
            motionStartTime = Time.unscaledTime;
            motionSettled = false;
        }

        private void Update()
        {
            if (!motionActive) return;
            if (!motionSettled)
            {
                float p = Mathf.Clamp01((Time.unscaledTime - motionStartTime) / motionDuration);
                float e = groupMotion == GroupMotion.Hovered ? BackOut(p) : p;
                lift.localScale = Vector3.one * Mathf.LerpUnclamped(startScale, targetScale, e);
                SetLiftY(Mathf.LerpUnclamped(startY, targetY, e));
                if (p >= 1f) motionSettled = true;
                return;
            }
            if (groupMotion != GroupMotion.Idle || !breathes) return;
            breathClock += Time.unscaledDeltaTime;
            float y = breathClock < 0f
                ? -BreathAmplitude
                : -BreathAmplitude * Mathf.Cos(breathClock / BreathPeriod * 2f * Mathf.PI);
            SetLiftY(y);
        }

        private void SetLiftY(float y)
        {
            Vector2 position = lift.anchoredPosition;
            position.y = y;
            lift.anchoredPosition = position;
        }

        // Overshoots the target by about a tenth of the travel before settling.
        private static float BackOut(float p)
        {
            const float s = 1.70158f;
            p -= 1f;
            return 1f + p * p * ((s + 1f) * p + s);
        }
        #endregion
    }
}
