using System.Collections;
using System.Collections.Generic;
using Memori.SaveData;
using TJ.Ordeals;
using TJ.Recruit;
using TMPro;
using UnityEngine;
using UnityEngine.EventSystems;
using UnityEngine.UI;

namespace TJ
{
    /// <summary>
    /// The UI of a pick-one panel (Prestige III traits, Ordeals, Treasure), generated by ChoicePanelBuilder: a title block
    /// over the map and a row of standing cards, with an optional squad card, Ordeal header or wide card. The panel fills it.
    /// </summary>
    public class ChoicePanelView : MonoBehaviour
    {
        // Past this many held Ordeals, the last pip becomes a "+N" pip, as on the HUD strip.
        private const int MAX_HELD_ICONS = 8;

        [SerializeField] private RectTransform titleBlock;
        [SerializeField] private CanvasGroup titleGroup;
        [SerializeField] private TMP_Text title;
        [SerializeField] private TMP_Text subtitle;
        [SerializeField] private Transform cardParent;
        [SerializeField] private ChoiceCardView cardPrefab;
        [SerializeField] private Vector2 cardSize = new(330f, 470f);
        [SerializeField] private float cardStagger = 0.07f;
        [SerializeField] private float titleDrop = 24f;
        [SerializeField] private float titleSeconds = 0.25f;

        #region Ordeal header
        [SerializeField] private GameObject infoRow;
        [SerializeField] private TMP_Text renownText;
        [SerializeField] private GameObject heldGroup;
        [SerializeField] private Transform heldParent;
        [SerializeField] private OrdealIcon heldIconPrefab;
        #endregion

        #region Squad card
        [SerializeField] private RectTransform recruitSlot;
        [SerializeField] private RecruitCard recruitCardPrefab;
        #endregion

        #region Treasure
        [Tooltip("Cards move like the recruit cards: the hovered one grows, the rest shrink, idle cards breathe.")]
        [SerializeField] private bool groupHover;
        [SerializeField] private TMP_Text countText;
        [SerializeField] private GameObject wideGroup;
        [SerializeField] private RectTransform wideSlot;
        [SerializeField] private ChoiceCardView wideCardPrefab;
        [SerializeField] private Vector2 wideCardSize = new(560f, 104f);
        [Tooltip("Stack bottom padding while the wide card is hidden, so the cards stay centred in the same space.")]
        [SerializeField] private int paddingWithoutWide;
        [SerializeField] private VerticalLayoutGroup stackLayout;
        #endregion

        private readonly List<ChoiceCardView> cards = new();
        private readonly List<OrdealIcon> heldIcons = new();
        private RecruitCard recruitCard;
        private ChoiceCardView wideCard;
        private ChoiceCardView hoveredCard;
        private Vector2 titleHome;
        private bool titleHomeSet;
        private Coroutine titleRoutine;

        public IReadOnlyList<ChoiceCardView> Cards => cards;
        public ChoiceCardView WideCard => wideCard;

        public void SetTitle(string titleText, string subtitleText)
        {
            title.text = titleText;
            subtitle.text = subtitleText;
        }

        public void SetInfo(string renownLine, CampaignSaveData run)
        {
            if (infoRow == null) return;
            infoRow.SetActive(true);
            renownText.text = renownLine;
            foreach (OrdealIcon icon in heldIcons)
                if (icon != null) Destroy(icon.gameObject);
            heldIcons.Clear();

            List<OrdealId> held = run.ordeals ?? new List<OrdealId>();
            heldGroup.SetActive(held.Count > 0);
            int shown = held.Count > MAX_HELD_ICONS ? MAX_HELD_ICONS - 1 : held.Count;
            for (int i = 0; i < shown; i++)
            {
                OrdealIcon icon = Instantiate(heldIconPrefab, heldParent);
                icon.Load(OrdealRegistry.Get(held[i]), run);
                heldIcons.Add(icon);
            }
            if (held.Count > MAX_HELD_ICONS)
            {
                OrdealIcon more = Instantiate(heldIconPrefab, heldParent);
                more.LoadOverflow(held.GetRange(shown, held.Count - shown));
                heldIcons.Add(more);
            }
        }

        public RecruitCard ShowRecruitCard()
        {
            if (recruitCard != null) Destroy(recruitCard.gameObject);
            recruitCard = Instantiate(recruitCardPrefab, recruitSlot);
            RectTransform rect = (RectTransform)recruitCard.transform;
            rect.anchorMin = rect.anchorMax = rect.pivot = new Vector2(0.5f, 0.5f);
            rect.anchoredPosition = Vector2.zero;
            return recruitCard;
        }

        public ChoiceCardView AddCard()
        {
            ChoiceCardView card = Instantiate(cardPrefab, cardParent);
            card.SetSize(cardSize);
            cards.Add(card);
            JoinGroup(card, cards.Count - 1);
            return card;
        }

        /// <summary>The single wide card under the row (the Treasure consumable). Call ShowWide(true) first.</summary>
        public ChoiceCardView AddWideCard()
        {
            if (wideCard != null) Destroy(wideCard.gameObject);
            wideCard = Instantiate(wideCardPrefab, wideSlot);
            wideCard.SetSize(wideCardSize);
            // The wide card grows and shrinks with the group but stays still at rest.
            JoinGroup(wideCard, cards.Count, false);
            return wideCard;
        }

        public void ShowWide(bool shown)
        {
            if (wideGroup == null) return;
            wideGroup.SetActive(shown);
            RectOffset padding = stackLayout.padding;
            // A new RectOffset, because editing the old one in place does not mark the layout for a rebuild.
            stackLayout.padding = new RectOffset(padding.left, padding.right, padding.top, shown ? 0 : paddingWithoutWide);
        }

        public void SetCounts(string line)
        {
            if (countText != null) countText.text = line;
        }

        public void Clear()
        {
            foreach (ChoiceCardView card in cards)
                if (card != null) Destroy(card.gameObject);
            cards.Clear();
            if (recruitCard != null) Destroy(recruitCard.gameObject);
            recruitCard = null;
            if (wideCard != null) Destroy(wideCard.gameObject);
            wideCard = null;
            hoveredCard = null;
        }

        /// <summary>Left and right move between the cards; down goes to the wide card and up comes back.</summary>
        public void WireNavigation()
        {
            Button wide = wideCard != null ? wideCard.Button : null;
            for (int i = 0; i < cards.Count; i++)
            {
                Navigation navigation = new()
                {
                    mode = Navigation.Mode.Explicit,
                    selectOnLeft = i > 0 ? cards[i - 1].Button : null,
                    selectOnRight = i < cards.Count - 1 ? cards[i + 1].Button : null,
                    selectOnDown = wide,
                };
                cards[i].Button.navigation = navigation;
            }
            if (wide != null)
                wide.navigation = new Navigation
                {
                    mode = Navigation.Mode.Explicit,
                    selectOnUp = cards.Count > 0 ? cards[cards.Count / 2].Button : null,
                };
        }

        #region Group hover
        private void JoinGroup(ChoiceCardView card, int index, bool breathe = true)
        {
            if (!groupHover) return;
            card.UseGroupHover(index, breathe);
            card.HoverChanged += OnCardHoverChanged;
            card.MotionStarted += _ => SetHovered(hoveredCard);
        }

        private void OnCardHoverChanged(ChoiceCardView card, bool on)
        {
            if (on) SetHovered(card);
            else if (hoveredCard == card) SetHovered(null);
        }

        // One hovered card grows and lifts; the rest shrink. Null returns every card to its breath.
        private void SetHovered(ChoiceCardView hovered)
        {
            hoveredCard = hovered;
            foreach (ChoiceCardView card in cards) ApplyHover(card, hovered);
            if (wideCard != null) ApplyHover(wideCard, hovered);
        }

        private static void ApplyHover(ChoiceCardView card, ChoiceCardView hovered)
        {
            if (card == null) return;
            card.SetGroupMotion(hovered == null ? ChoiceCardView.GroupMotion.Idle
                : card == hovered ? ChoiceCardView.GroupMotion.Hovered
                : ChoiceCardView.GroupMotion.Neighbour);
        }
        #endregion

        public void PlayOpen()
        {
            for (int i = 0; i < cards.Count; i++) cards[i].PlayEnter(i * cardStagger);
            if (wideCard != null) wideCard.PlayEnter(cards.Count * cardStagger);
            if (!titleHomeSet)
            {
                titleHome = titleBlock.anchoredPosition;
                titleHomeSet = true;
            }
            if (titleRoutine != null) StopCoroutine(titleRoutine);
            titleRoutine = isActiveAndEnabled ? StartCoroutine(DropTitle()) : null;
            if (titleRoutine == null)
            {
                titleGroup.alpha = 1f;
                titleBlock.anchoredPosition = titleHome;
            }
        }

        private IEnumerator DropTitle()
        {
            for (float t = 0f; t < titleSeconds; t += Time.unscaledDeltaTime)
            {
                float k = 1f - Mathf.Pow(1f - t / titleSeconds, 3f);
                titleGroup.alpha = k;
                titleBlock.anchoredPosition = titleHome + new Vector2(0f, Mathf.Lerp(titleDrop, 0f, k));
                yield return null;
            }
            titleGroup.alpha = 1f;
            titleBlock.anchoredPosition = titleHome;
            titleRoutine = null;
        }

        /// <summary>Selects the first card for keyboard and controller players, so they can pick without the mouse.</summary>
        public void FocusFirstCard()
        {
            if (cards.Count == 0 || ChoiceCardView.PointerUsedLast()) return;
            EventSystem eventSystem = EventSystem.current;
            if (eventSystem != null) eventSystem.SetSelectedGameObject(cards[0].Button.gameObject);
        }
    }
}
