using System.Collections;
using Memori.Tooltip;
using Memori.UI;
using TMPro;
using UnityEngine;
using UnityEngine.UI;

namespace TJ.Town
{
    /// <summary>
    /// The town panel's UI, generated by TownPanelBuilder. TownPanel fills it; this class only shows what it is given.
    /// </summary>
    public class TownPanelView : MonoBehaviour
    {
        public enum Road { Undecided, Entered, Sacked }

        #region Header
        [SerializeField] private TMP_Text townName;
        [SerializeField] private TMP_Text townSubtitle;
        [SerializeField] private Image factionBand;
        // The project renders in linear colour, so this reads about twice as strong as its value on screen.
        [SerializeField, Range(0f, 1f)] private float factionBandAlpha = 0.12f;
        [SerializeField] private GameObject townInfoButton;
        [SerializeField] private MemoriTooltipTrigger townInfoTooltip;
        [SerializeField] private GameObject enteredMark;
        [SerializeField] private GameObject sackedMark;
        #endregion

        #region Enter Town
        [SerializeField] private CanvasGroup enterColumn;
        [SerializeField] private TMP_Text healLabel;
        [SerializeField] private TMP_Text healValue;
        [SerializeField] private TMP_Text recruitsValue;
        [SerializeField] private TMP_Text costValue;
        [SerializeField] private TMP_Text healLine;
        [SerializeField] private TMP_Text recruitLine;
        [SerializeField] private TMP_Text recruitNote;
        [SerializeField] private GameObject recruitRow;
        [SerializeField] private Button recruitButton;
        [SerializeField] private TMP_Text recruitCost;
        [SerializeField] private GameObject recruitDone;
        [SerializeField] private Button enterButton;
        [SerializeField] private GameObject enterNotTaken;
        #endregion

        #region Fight Garrison
        [SerializeField] private CanvasGroup fightColumn;
        // Shown on the sacked road only, where it carries the garrison result.
        [SerializeField] private TMP_Text fightSubtitle;
        [SerializeField] private TMP_Text battlefieldValue;
        [SerializeField] private Image weatherIcon;
        [SerializeField] private TMP_Text weatherValue;
        [SerializeField] private MemoriTooltipTrigger weatherTooltip;
        [SerializeField] private Sprite[] weatherIcons;
        [SerializeField] private TMP_Text bountyValue;
        [SerializeField] private GameObject garrisonBlock;
        [SerializeField] private LayoutElement garrisonTray;
        [SerializeField] private RectTransform garrisonGrid;
        [SerializeField] private GridLayoutGroup garrisonGridLayout;
        [SerializeField] private float garrisonTrayPadding = 8f;
        [SerializeField] private int garrisonSingleRowMax = 9;
        [SerializeField] private GameObject fightLines;
        [SerializeField] private GameObject gearLine;
        [SerializeField] private TMP_Text gearLineText;
        [SerializeField] private MemoriTooltipTrigger gearLineTooltip;
        [SerializeField] private TMP_Text fightPrediction;
        [SerializeField] private GameObject spoilsBlock;
        [SerializeField] private TownSpoilRow goldRow;
        [SerializeField] private TownSpoilRow gearRow;
        [SerializeField] private TownSpoilRow conscriptRow;
        [SerializeField] private TMP_Text eliteRavagersText;
        [SerializeField] private MemoriTooltipTrigger eliteRavagersTooltip;
        [SerializeField] private Button fightButton;
        [SerializeField] private GameObject fightNotTaken;
        #endregion

        [SerializeField, Range(0f, 1f)] private float notTakenAlpha = 0.34f;
        [SerializeField] private float roadFadeSeconds = 0.25f;

        private Coroutine roadFade;

        public Button EnterButton => enterButton;
        public Button FightButton => fightButton;
        public Button RecruitButton => recruitButton;
        public TownSpoilRow GoldRow => goldRow;
        public TownSpoilRow GearRow => gearRow;
        public TownSpoilRow ConscriptRow => conscriptRow;
        public RectTransform GarrisonGrid => garrisonGrid;

        #region Header
        // The subtitle already names the size; the size argument is unused until TownPanel stops passing it.
        public void SetHeader(string name, string subtitle, Color faction, TownSize size)
        {
            townName.text = name;
            townSubtitle.text = subtitle;
            factionBand.color = new Color(faction.r, faction.g, faction.b, factionBandAlpha);
        }

        public void SetTownInfo(TooltipContent content) => townInfoTooltip.SetUpToolTip(content);
        #endregion

        #region Enter Town
        public void SetEnterStrip(string healTitle, string heal, string recruits)
        {
            healLabel.text = healTitle;
            healValue.text = heal;
            recruitsValue.text = recruits;
        }

        // The strip and the recruit button show the same price, so both change together.
        public void SetCost(string cost)
        {
            costValue.text = cost;
            recruitCost.text = cost;
        }

        public void SetEnterLines(string heal, string recruit, string note)
        {
            healLine.text = heal;
            recruitLine.text = recruit;
            recruitNote.text = note;
        }

        // A used recruit hides its button rather than fading it, as the town's spoils do.
        public void SetRecruitAvailable(bool available)
        {
            recruitButton.gameObject.SetActive(available);
            recruitCost.gameObject.SetActive(available);
            recruitDone.SetActive(!available);
        }
        #endregion

        #region Fight Garrison
        public void SetFightSubtitle(string text) => fightSubtitle.text = text;

        public void SetBattlefield(string text) => battlefieldValue.text = text;

        public void SetWeather(Weather weather, string name, string description)
        {
            weatherValue.text = name;
            int index = (int)weather;
            if (index >= 0 && index < weatherIcons.Length) weatherIcon.sprite = weatherIcons[index];
            weatherTooltip.SetUpToolTip(name, description);
        }

        public void SetBounty(string text) => bountyValue.text = text;

        // The gear a sack would win; hidden for a town that holds none.
        public void SetGearPreview(string text, string tooltipTitle, string tooltipBody)
        {
            bool show = !string.IsNullOrEmpty(text);
            gearLine.SetActive(show);
            if (!show) return;
            gearLineText.text = text;
            gearLineTooltip.SetUpToolTip(tooltipTitle, tooltipBody);
        }

        public void SetPrediction(string text) => fightPrediction.text = text;

        // One row up to garrisonSingleRowMax squads, two above that. The grid is scaled, so the tray height is set here.
        public void SetGarrisonCount(int count)
        {
            bool oneRow = count <= garrisonSingleRowMax;
            int columns = oneRow ? Mathf.Max(count, 1) : Mathf.CeilToInt(count / 2f);
            int rows = oneRow ? 1 : 2;
            garrisonGridLayout.constraintCount = columns;
            Vector2 cell = garrisonGridLayout.cellSize;
            Vector2 gap = garrisonGridLayout.spacing;
            var size = new Vector2(columns * cell.x + (columns - 1) * gap.x, rows * cell.y + (rows - 1) * gap.y);
            garrisonGrid.sizeDelta = size;
            garrisonTray.minHeight = garrisonTray.preferredHeight = size.y * garrisonGrid.localScale.y + garrisonTrayPadding * 2f;
        }

        public void SetEliteRavagers(string text, string tooltipTitle, string tooltipBody)
        {
            bool show = !string.IsNullOrEmpty(text);
            eliteRavagersText.gameObject.SetActive(show);
            if (!show) return;
            eliteRavagersText.text = text;
            eliteRavagersTooltip.SetUpToolTip(tooltipTitle, tooltipBody);
        }
        #endregion

        #region Road
        public void ShowRoad(Road road, bool animate)
        {
            bool undecided = road == Road.Undecided;
            bool entered = road == Road.Entered;
            bool sacked = road == Road.Sacked;

            townInfoButton.SetActive(undecided);
            enteredMark.SetActive(entered);
            sackedMark.SetActive(sacked);

            enterButton.gameObject.SetActive(undecided);
            enterNotTaken.SetActive(sacked);
            recruitRow.SetActive(entered);

            fightButton.gameObject.SetActive(undecided);
            fightNotTaken.SetActive(entered);
            fightSubtitle.gameObject.SetActive(sacked);
            garrisonBlock.SetActive(!sacked);
            fightLines.SetActive(!sacked);
            spoilsBlock.SetActive(sacked);

            // The road the player did not take stays on screen, greyed out.
            float enterAlpha = sacked ? notTakenAlpha : 1f;
            float fightAlpha = entered ? notTakenAlpha : 1f;
            SetInteractable(enterColumn, !sacked);
            SetInteractable(fightColumn, !entered);
            if (roadFade != null) StopCoroutine(roadFade);
            roadFade = null;
            if (animate && isActiveAndEnabled && roadFadeSeconds > 0f)
            {
                roadFade = StartCoroutine(FadeColumns(enterAlpha, fightAlpha));
                return;
            }
            enterColumn.alpha = enterAlpha;
            fightColumn.alpha = fightAlpha;
        }

        private static void SetInteractable(CanvasGroup column, bool interactable)
        {
            column.interactable = interactable;
            column.blocksRaycasts = interactable;
        }

        private IEnumerator FadeColumns(float enterTarget, float fightTarget)
        {
            float enterStart = enterColumn.alpha;
            float fightStart = fightColumn.alpha;
            for (float t = 0f; t < roadFadeSeconds; t += Time.unscaledDeltaTime)
            {
                float k = UIJuice.EaseOutCubic(t / roadFadeSeconds);
                enterColumn.alpha = Mathf.Lerp(enterStart, enterTarget, k);
                fightColumn.alpha = Mathf.Lerp(fightStart, fightTarget, k);
                yield return null;
            }
            enterColumn.alpha = enterTarget;
            fightColumn.alpha = fightTarget;
            roadFade = null;
        }
        #endregion

        #region Moments
        // Entering: the Entered mark punches and the recruit row deals in.
        public void PlayEntered()
        {
            if (!isActiveAndEnabled) return;
            StartCoroutine(UIJuice.Punch(enteredMark.transform, 1.08f));
            StartCoroutine(UIJuice.Reveal(new[] { (RectTransform)recruitRow.transform }, new[] { 0.1f }, 0.3f));
        }

        // Sacking: the Sacked mark punches and the three spoils deal in one after another.
        public void PlaySacked()
        {
            if (!isActiveAndEnabled) return;
            StartCoroutine(UIJuice.Punch(sackedMark.transform, 1.08f));
            var rows = new[] { (RectTransform)goldRow.transform, (RectTransform)gearRow.transform, (RectTransform)conscriptRow.transform };
            StartCoroutine(UIJuice.Reveal(rows, new[] { 0.1f, 0.2f, 0.3f }, 0.3f));
        }
        #endregion
    }
}
