using System.Collections;
using Memori.Tooltip;
using TMPro;
using UnityEngine;
using UnityEngine.UI;

namespace TJ.Town
{
    /// <summary>
    /// The town panel's UI, generated by TownPanelBuilder. TownPanel fills it; this class only shows what it is given.
    /// </summary>
    public class TownPanelView : MonoBehaviour
    {
        public enum Road { Undecided, Entered, Sacked }

        #region Header
        [SerializeField] private TMP_Text townName;
        [SerializeField] private TMP_Text townSubtitle;
        [SerializeField] private Image factionBand;
        // The project renders in linear colour, so this reads about twice as strong as its value on screen.
        [SerializeField, Range(0f, 1f)] private float factionBandAlpha = 0.12f;
        [SerializeField] private Image[] sizeFills;
        [SerializeField] private Image[] sizeBorders;
        [SerializeField] private Image[] sizeGlows;
        [SerializeField] private TMP_Text[] sizeLabels;
        [SerializeField] private Image[] sizeLinks;
        [SerializeField] private Color sizeReached = new(0.914f, 0.753f, 0.416f, 1f);
        [SerializeField] private Color sizeReachedBorder = new(0.69f, 0.541f, 0.243f, 1f);
        [SerializeField] private Color sizeEmpty = new(0.086f, 0.125f, 0.137f, 1f);
        [SerializeField] private Color sizeEmptyBorder = new(0.337f, 0.376f, 0.373f, 1f);
        [SerializeField] private Color sizeLabelCurrent = new(0.914f, 0.753f, 0.416f, 1f);
        [SerializeField] private Color sizeLabelReached = new(0.706f, 0.667f, 0.58f, 1f);
        [SerializeField] private Color sizeLabelEmpty = new(0.424f, 0.467f, 0.482f, 1f);
        [SerializeField] private GameObject townInfoButton;
        [SerializeField] private MemoriTooltipTrigger townInfoTooltip;
        [SerializeField] private GameObject enteredPill;
        [SerializeField] private GameObject sackedPill;
        [SerializeField] private GameObject orMark;
        #endregion

        #region Enter Town
        [SerializeField] private CanvasGroup enterColumn;
        [SerializeField] private TMP_Text healLabel;
        [SerializeField] private TMP_Text healValue;
        [SerializeField] private TMP_Text recruitsValue;
        [SerializeField] private TMP_Text costValue;
        [SerializeField] private TMP_Text healLine;
        [SerializeField] private TMP_Text recruitLine;
        [SerializeField] private TMP_Text recruitNote;
        [SerializeField] private GameObject recruitRow;
        [SerializeField] private Button recruitButton;
        [SerializeField] private TMP_Text recruitCost;
        [SerializeField] private GameObject recruitDone;
        [SerializeField] private Button enterButton;
        [SerializeField] private Button enterContinueButton;
        [SerializeField] private GameObject enterNotTaken;
        #endregion

        #region Fight Garrison
        [SerializeField] private CanvasGroup fightColumn;
        [SerializeField] private TMP_Text fightSubtitle;
        [SerializeField] private TMP_Text battlefieldValue;
        [SerializeField] private Image weatherIcon;
        [SerializeField] private TMP_Text weatherValue;
        [SerializeField] private MemoriTooltipTrigger weatherTooltip;
        [SerializeField] private Sprite[] weatherIcons;
        [SerializeField] private TMP_Text bountyValue;
        [SerializeField] private GameObject garrisonBlock;
        [SerializeField] private TMP_Text garrisonCount;
        [SerializeField] private LayoutElement garrisonTray;
        [SerializeField] private RectTransform garrisonGrid;
        [SerializeField] private GridLayoutGroup garrisonGridLayout;
        [SerializeField] private float garrisonTrayPadding = 8f;
        [SerializeField] private int garrisonSingleRowMax = 9;
        [SerializeField] private GameObject fightLines;
        [SerializeField] private GameObject spoilsBlock;
        [SerializeField] private TownSpoilRow goldRow;
        [SerializeField] private TownSpoilRow gearRow;
        [SerializeField] private TownSpoilRow conscriptRow;
        [SerializeField] private TMP_Text eliteRavagersText;
        [SerializeField] private MemoriTooltipTrigger eliteRavagersTooltip;
        [SerializeField] private Button fightButton;
        [SerializeField] private Button fightContinueButton;
        [SerializeField] private GameObject fightNotTaken;
        #endregion

        [SerializeField, Range(0f, 1f)] private float notTakenAlpha = 0.34f;
        [SerializeField] private float roadFadeSeconds = 0.25f;

        private Coroutine roadFade;

        public Button EnterButton => enterButton;
        public Button FightButton => fightButton;
        public Button RecruitButton => recruitButton;
        public Button EnterContinueButton => enterContinueButton;
        public Button FightContinueButton => fightContinueButton;
        public TownSpoilRow GoldRow => goldRow;
        public TownSpoilRow GearRow => gearRow;
        public TownSpoilRow ConscriptRow => conscriptRow;
        public RectTransform GarrisonGrid => garrisonGrid;

        #region Header
        public void SetHeader(string name, string subtitle, Color faction, TownSize size)
        {
            townName.text = name;
            townSubtitle.text = subtitle;
            factionBand.color = new Color(faction.r, faction.g, faction.b, factionBandAlpha);

            int current = (int)size;
            for (int i = 0; i < sizeFills.Length; i++)
            {
                bool reached = i <= current;
                sizeFills[i].color = reached ? sizeReached : sizeEmpty;
                sizeBorders[i].color = reached ? sizeReachedBorder : sizeEmptyBorder;
                sizeGlows[i].enabled = i == current;
                sizeLabels[i].color = i == current ? sizeLabelCurrent : reached ? sizeLabelReached : sizeLabelEmpty;
            }
            for (int i = 0; i < sizeLinks.Length; i++)
                sizeLinks[i].color = i < current ? sizeReachedBorder : sizeEmptyBorder;
        }

        public void SetTownInfo(string title, string body) => townInfoTooltip.SetUpToolTip(title, body);
        #endregion

        #region Enter Town
        public void SetEnterStrip(string healTitle, string heal, string recruits)
        {
            healLabel.text = healTitle;
            healValue.text = heal;
            recruitsValue.text = recruits;
        }

        // The strip and the recruit button show the same price, so both change together.
        public void SetCost(string cost)
        {
            costValue.text = cost;
            recruitCost.text = cost;
        }

        public void SetEnterLines(string heal, string recruit, string note)
        {
            healLine.text = heal;
            recruitLine.text = recruit;
            recruitNote.text = note;
        }

        // A used recruit hides its button rather than fading it, as the town's spoils do.
        public void SetRecruitAvailable(bool available)
        {
            recruitButton.gameObject.SetActive(available);
            recruitCost.gameObject.SetActive(available);
            recruitDone.SetActive(!available);
        }
        #endregion

        #region Fight Garrison
        public void SetFightSubtitle(string text) => fightSubtitle.text = text;

        public void SetBattlefield(string text) => battlefieldValue.text = text;

        public void SetWeather(Weather weather, string name, string description)
        {
            weatherValue.text = name;
            int index = (int)weather;
            if (index >= 0 && index < weatherIcons.Length) weatherIcon.sprite = weatherIcons[index];
            weatherTooltip.SetUpToolTip(name, description);
        }

        public void SetBounty(string text) => bountyValue.text = text;

        // One row up to garrisonSingleRowMax squads, two above that. The grid is scaled, so the tray height is set here.
        public void SetGarrisonCount(int count, string countText)
        {
            garrisonCount.text = countText;
            bool oneRow = count <= garrisonSingleRowMax;
            int columns = oneRow ? Mathf.Max(count, 1) : Mathf.CeilToInt(count / 2f);
            int rows = oneRow ? 1 : 2;
            garrisonGridLayout.constraintCount = columns;
            Vector2 cell = garrisonGridLayout.cellSize;
            Vector2 gap = garrisonGridLayout.spacing;
            var size = new Vector2(columns * cell.x + (columns - 1) * gap.x, rows * cell.y + (rows - 1) * gap.y);
            garrisonGrid.sizeDelta = size;
            garrisonTray.minHeight = garrisonTray.preferredHeight = size.y * garrisonGrid.localScale.y + garrisonTrayPadding * 2f;
        }

        public void SetEliteRavagers(string text, string tooltipTitle, string tooltipBody)
        {
            bool show = !string.IsNullOrEmpty(text);
            eliteRavagersText.gameObject.SetActive(show);
            if (!show) return;
            eliteRavagersText.text = text;
            eliteRavagersTooltip.SetUpToolTip(tooltipTitle, tooltipBody);
        }
        #endregion

        #region Road
        public void ShowRoad(Road road, bool animate)
        {
            bool undecided = road == Road.Undecided;
            bool entered = road == Road.Entered;
            bool sacked = road == Road.Sacked;

            townInfoButton.SetActive(undecided);
            enteredPill.SetActive(entered);
            sackedPill.SetActive(sacked);
            orMark.SetActive(undecided);

            enterButton.gameObject.SetActive(undecided);
            enterContinueButton.gameObject.SetActive(entered);
            enterNotTaken.SetActive(sacked);
            recruitRow.SetActive(entered);

            fightButton.gameObject.SetActive(undecided);
            fightContinueButton.gameObject.SetActive(sacked);
            fightNotTaken.SetActive(entered);
            garrisonBlock.SetActive(!sacked);
            fightLines.SetActive(!sacked);
            spoilsBlock.SetActive(sacked);

            // The road the player did not take stays on screen, greyed out.
            float enterAlpha = sacked ? notTakenAlpha : 1f;
            float fightAlpha = entered ? notTakenAlpha : 1f;
            SetInteractable(enterColumn, !sacked);
            SetInteractable(fightColumn, !entered);
            if (roadFade != null) StopCoroutine(roadFade);
            roadFade = null;
            if (animate && isActiveAndEnabled && roadFadeSeconds > 0f)
            {
                roadFade = StartCoroutine(FadeColumns(enterAlpha, fightAlpha));
                return;
            }
            enterColumn.alpha = enterAlpha;
            fightColumn.alpha = fightAlpha;
        }

        private static void SetInteractable(CanvasGroup column, bool interactable)
        {
            column.interactable = interactable;
            column.blocksRaycasts = interactable;
        }

        private IEnumerator FadeColumns(float enterTarget, float fightTarget)
        {
            float enterStart = enterColumn.alpha;
            float fightStart = fightColumn.alpha;
            for (float t = 0f; t < roadFadeSeconds; t += Time.unscaledDeltaTime)
            {
                float k = t / roadFadeSeconds;
                enterColumn.alpha = Mathf.Lerp(enterStart, enterTarget, k);
                fightColumn.alpha = Mathf.Lerp(fightStart, fightTarget, k);
                yield return null;
            }
            enterColumn.alpha = enterTarget;
            fightColumn.alpha = fightTarget;
            roadFade = null;
        }
        #endregion
    }
}
