using System.Collections.Generic;
using Memori.Audio;
using Memori.UI;
using TJ.Map;
using TMPro;
using UnityEngine;
using UnityEngine.UI;

namespace TJ.Campfire
{
    /// <summary>
    /// The campfire panel's UI, generated by CampfirePanelBuilder. CampfirePanel fills it; this class only shows what it is given.
    /// </summary>
    public class CampfirePanelView : MonoBehaviour
    {
        public enum State { Choosing, Train, Result }

        #region Header
        [SerializeField] private TMP_Text headerTitle;
        #endregion

        #region Choosing
        [SerializeField] private GameObject choosingBody;
        [SerializeField] private Button restButton;
        [SerializeField] private Button trainButton;
        [SerializeField] private Button scavengeButton;
        [SerializeField] private Button scoutButton;
        [SerializeField] private TMP_Text restHealValue;
        [SerializeField] private TMP_Text restLine;
        [SerializeField] private TMP_Text trainCostValue;
        [SerializeField] private TMP_Text trainCountLine;
        [SerializeField] private TMP_Text trainPricesLine;
        [SerializeField] private GameObject trainUnavailable;
        [SerializeField] private TMP_Text scavengeGearValue;
        [SerializeField] private TMP_Text scavengeLine;
        [SerializeField] private TMP_Text scoutGoldValue;
        [SerializeField] private TMP_Text scoutConsumableLine;
        [SerializeField] private Image scoutConsumableIcon;
        [SerializeField] private MapOverviewHoverTrigger scoutMapTrigger;
        [SerializeField] private Color lineColour = new(0.925f, 0.902f, 0.847f, 1f);
        [SerializeField] private Color lineIconColour = new(0.706f, 0.667f, 0.580f, 1f);
        [SerializeField] private Color warningColour = new(0.890f, 0.412f, 0.369f, 1f);
        #endregion

        #region Train
        [SerializeField] private GameObject trainBody;
        [SerializeField] private RectTransform deployedRow;
        [SerializeField] private RectTransform reserveRow;
        [SerializeField] private GameObject reserveGroup;
        [SerializeField] private TMP_Text trainCanCount;
        [SerializeField] private TMP_Text trainDetail;
        [SerializeField] private Button backButton;
        [SerializeField] private CampfireTrainSlot slotPrefab;
        #endregion

        #region Result
        [SerializeField] private GameObject resultBody;
        [SerializeField] private Image resultIcon;
        [Tooltip("Round glow behind the result mount; plays as the result lands.")]
        [SerializeField] private UIFlare resultHalo;
        [SerializeField] private TMP_Text resultTitle;
        [SerializeField] private TMP_Text resultDescription;
        [SerializeField] private GameObject[] resultCells;
        [SerializeField] private TMP_Text[] resultLabels;
        [SerializeField] private TMP_Text[] resultValues;
        [SerializeField] private Sprite restIcon;
        [SerializeField] private Sprite trainIcon;
        [SerializeField] private Sprite scavengeIcon;
        [SerializeField] private Sprite scoutIcon;
        #endregion

        private readonly List<CampfireTrainSlot> slots = new();

        public Button RestButton => restButton;
        public Button TrainButton => trainButton;
        public Button ScavengeButton => scavengeButton;
        public Button ScoutButton => scoutButton;
        public Button BackButton => backButton;

        public void SetUp(MapOverviewPanel mapOverviewPanel, MapSceneUIManager mapSceneUIManager)
        {
            if (scoutMapTrigger != null) scoutMapTrigger.SetUp(mapOverviewPanel, mapSceneUIManager);
        }

        public void SetHeader(string title) => headerTitle.text = title;

        public void ShowState(State state)
        {
            choosingBody.SetActive(state == State.Choosing);
            trainBody.SetActive(state == State.Train);
            resultBody.SetActive(state == State.Result);
        }

        #region Choosing
        public void SetRest(string heal, string line)
        {
            restHealValue.text = heal;
            restLine.text = line;
        }

        // With no squad to train the button gives way to a plain line, rather than a faded button.
        public void SetTrain(string cost, string countLine, string pricesLine, bool available)
        {
            trainCostValue.text = cost;
            trainCountLine.text = countLine;
            trainPricesLine.text = pricesLine;
            trainButton.gameObject.SetActive(available);
            trainUnavailable.SetActive(!available);
        }

        public void SetScavenge(string gear, string line)
        {
            scavengeGearValue.text = gear;
            scavengeLine.text = line;
        }

        public void SetScout(string gold, string consumableLine, bool slotsFull)
        {
            scoutGoldValue.text = gold;
            scoutConsumableLine.text = consumableLine;
            scoutConsumableLine.color = slotsFull ? warningColour : lineColour;
            scoutConsumableIcon.color = slotsFull ? warningColour : lineIconColour;
        }

        private Coroutine choiceStagger;

        // The choice columns arrive one after another, each with the option sound, like the Games columns.
        public void StaggerChoices()
        {
            var columns = new List<RectTransform>();
            foreach (Transform child in choosingBody.transform)
                if (child.gameObject.activeSelf && child is RectTransform rect && child.GetComponentInChildren<Button>(true) != null) columns.Add(rect);
            if (choiceStagger != null) StopCoroutine(choiceStagger);
            choiceStagger = StartCoroutine(UIJuice.Stagger(columns, 0.1f, 0.22f, 0f, _ => IAudioRequester.Instance.PlaySFX(SFXData.EventOptionLoad)));
        }

        public void SetChoicesInteractable(bool interactable)
        {
            restButton.interactable = interactable;
            trainButton.interactable = interactable;
            scavengeButton.interactable = interactable;
            scoutButton.interactable = interactable;
        }
        #endregion

        #region Train
        public void ClearSlots()
        {
            foreach (CampfireTrainSlot slot in slots)
                if (slot != null) Destroy(slot.gameObject);
            slots.Clear();
        }

        public CampfireTrainSlot AddSlot(bool inReserve)
        {
            CampfireTrainSlot slot = Instantiate(slotPrefab, inReserve ? reserveRow : deployedRow);
            slots.Add(slot);
            return slot;
        }

        public void SetTrainCounts(string canCount, bool hasReserve)
        {
            trainCanCount.text = canCount;
            trainDetail.text = string.Empty;
            reserveGroup.SetActive(hasReserve);
        }

        // A null detail clears the line when the cursor leaves a slot.
        public void SetTrainDetail(string detail) => trainDetail.text = detail ?? string.Empty;
        #endregion

        #region Result
        public void ShowResult(CampfirePanel.CampfireChoice choice, string title, string description, IReadOnlyList<(string label, string value)> cells)
        {
            resultIcon.sprite = choice switch
            {
                CampfirePanel.CampfireChoice.Rest => restIcon,
                CampfirePanel.CampfireChoice.Train => trainIcon,
                CampfirePanel.CampfireChoice.Scavenge => scavengeIcon,
                _ => scoutIcon,
            };
            resultTitle.text = title;
            resultDescription.text = description;
            for (int i = 0; i < resultCells.Length; i++)
            {
                bool used = cells != null && i < cells.Count;
                resultCells[i].SetActive(used);
                if (!used) continue;
                resultLabels[i].text = cells[i].label;
                resultValues[i].text = cells[i].value;
            }
            ShowState(State.Result);
            if (!isActiveAndEnabled) return;
            CanvasGroup group = resultBody.GetComponent<CanvasGroup>();
            if (group == null) group = resultBody.AddComponent<CanvasGroup>();
            StartCoroutine(UIJuice.Open(group, null, UIJuice.OpenTime, 0f));
            StartCoroutine(UIJuice.Punch(resultIcon.transform.parent, 1.1f));
            if (resultHalo != null) resultHalo.Play();
        }
        #endregion
    }
}
