using System;
using System.Collections;
using System.Collections.Generic;
using Memori.Audio;
using Memori.Tooltip;
using MoreMountains.Tools;
using TMPro;
using UnityEngine;
using UnityEngine.UI;

namespace TJ.Engagement
{
    /// <summary>
    /// The engagement panel's UI, generated by EngagementPanelBuilder. EngagementPanel fills it; this class only shows what it is given.
    /// </summary>
    public class EngagementPanelView : MonoBehaviour
    {
        #region Header
        [SerializeField] private Image headerBand;
        [SerializeField] private Image headerIcon;
        [SerializeField] private TMP_Text headerTitle;
        [SerializeField] private TMP_Text headerSubtitle;
        [SerializeField] private GameObject pill;
        [SerializeField] private TMP_Text pillText;
        [SerializeField] private MemoriTooltipTrigger pillTooltip;
        [SerializeField] private float bandAlpha = 0.12f;
        [SerializeField] private Sprite skirmishIcon;
        [SerializeField] private Sprite hordeIcon;
        [SerializeField] private Sprite garrisonIcon;
        [SerializeField] private Sprite victoryIcon;
        [SerializeField] private Sprite defeatIcon;
        #endregion

        #region Before the battle
        [SerializeField] private GameObject preBattleBody;
        [SerializeField] private RectTransform enemyArmySlot;
        [SerializeField] private RectTransform enemyArmyParent;
        [SerializeField] private TMP_Text battlefieldValue;
        [SerializeField] private Image battlefieldIcon;
        [SerializeField] private TMP_Text weatherValue;
        [SerializeField] private Image weatherIcon;
        [SerializeField] private MemoriTooltipTrigger weatherTooltip;
        [SerializeField] private GameObject heavensongGroup;
        [SerializeField] private Button heavensongButton;
        [SerializeField] private MemoriTooltipTrigger heavensongTooltip;
        [SerializeField] private GameObject warChestGroup;
        [SerializeField] private Button warChestButton;
        [SerializeField] private TMP_Text warChestNote;
        [SerializeField] private MemoriTooltipTrigger warChestTooltip;
        [SerializeField] private GameObject reserveWarning;
        [SerializeField] private Button autoResolveButton;
        [SerializeField] private TMP_Text autoResolvePrediction;
        [SerializeField] private AutoResolvePreview autoResolvePreview;
        [SerializeField] private MemoriTooltipTrigger autoResolveTooltip;
        [SerializeField] private GameObject autoResolveDisabled;
        [SerializeField] private Button fightButton;
        [SerializeField] private MemoriTooltipTrigger fightTooltip;
        [SerializeField] private Sprite plainsIcon;
        [SerializeField] private Sprite forestIcon;
        [SerializeField] private Sprite riverIcon;
        [SerializeField] private Sprite swampIcon;
        [SerializeField] private Sprite clearIcon;
        [SerializeField] private Sprite rainIcon;
        [SerializeField] private Sprite fogIcon;
        [SerializeField] private Sprite snowIcon;
        [SerializeField] private Color sunTint = new(0.949f, 0.784f, 0.400f, 1f);
        [SerializeField] private Color weatherTint = new(0.620f, 0.847f, 1f, 1f);
        #endregion

        #region After the battle
        [SerializeField] private GameObject resultBody;
        [SerializeField] private TMP_Text outcomeLine;
        [SerializeField] private MemoriTooltipTrigger detailedStats;
        [SerializeField] private RectTransform fallenSlot;
        [SerializeField] private TMP_Text[] reportLabels;
        [SerializeField] private TMP_Text[] reportValues;
        [SerializeField] private GameObject stacks;
        [SerializeField] private RectTransform spoilsParent;
        [SerializeField] private RectTransform choicesParent;
        [SerializeField] private GameObject noChoices;
        [SerializeField] private EngagementSpoilRow spoilRowPrefab;
        [SerializeField] private EngagementChoiceRow choiceRowPrefab;
        [SerializeField] private Sprite damageIcon;
        [SerializeField] private string chooseSfx = "upgrade-unlock";
        #endregion

        #region Reward icons
        [SerializeField] private Sprite goldIcon;
        [SerializeField] private Sprite recruitIcon;
        [SerializeField] private Sprite ransomIcon;
        [SerializeField] private Sprite conscriptIcon;
        [SerializeField] private Sprite raiseDeadIcon;
        [SerializeField] private Sprite consumeIcon;
        [SerializeField] private Sprite purgeIcon;
        [SerializeField] private Sprite hourOfDestinyIcon;
        #endregion

        #region Result pop-up
        [SerializeField] private Canvas resultOverlay;
        [SerializeField] private int overlaySortingOrder = 104;
        [SerializeField] private Image resultCover;
        [SerializeField] private Animator endBattlePopup;
        [SerializeField] private MemoriCanvasGroup endBattleContent;
        [SerializeField] private TMP_Text endBattleTitle;
        [SerializeField] private TMP_Text endBattleOutcome;
        [SerializeField] private float coverAlpha = 0.62f;
        [SerializeField] private float coverInSeconds = 0.22f;
        [Tooltip("Off since 2026-09-30: the battle's own Victory/Defeat card already shows the result, so the map no longer repeats it.")]
        [SerializeField] private bool showBattleBanner;
        [SerializeField] private float bannerHoldSeconds = 1f;
        [SerializeField] private float bannerLingerSeconds = 3f;
        [SerializeField] private float bannerFadeSeconds = 0.4f;
        [SerializeField] private float revealSeconds = 0.6f;
        #endregion

        #region Motion
        [SerializeField] private RectTransform card;
        [SerializeField] private float slideDistance = 1000f;
        [SerializeField] private float slideDelaySeconds = 0.2f;
        [SerializeField] private float slideSeconds = 0.5f;
        [SerializeField] private float closeSeconds = 0.25f;
        // Canvas units above the screen bottom the card must clear: the army bar's loss badges reach about 281 at every UI scale.
        [SerializeField] private float bottomClearance = 295f;
        // Canvas units below the screen top the card's edge may rise to: the top bar's 50 plus the 25 the crest stands above the edge.
        [SerializeField] private float topClearance = 75f;
        [SerializeField] private float minFitScale = 0.6f;
        #endregion

        // Cards are 60 wide with 5 between, the army bar's pitch; the fallen strip draws them at half size.
        const float CardPitch = 65f;
        const float CardHeight = 130f;
        const float FallenScale = 0.5f;
        const float WellPadding = 8f;

        private readonly List<EngagementSpoilRow> spoilRows = new();
        private readonly List<EngagementChoiceRow> choiceRows = new();
        private Vector2 cardRest;
        private float cardLift;
        private Vector3 fittedFor;
        private Coroutine rise;
        private Coroutine popup;
        private static readonly int ActiveParameter = Animator.StringToHash("Active");

        public RectTransform EnemyArmyParent => enemyArmyParent;
        public Button AutoResolveButton => autoResolveButton;
        public Button FightButton => fightButton;
        public Button HeavensongButton => heavensongButton;
        public Button WarChestButton => warChestButton;
        public AutoResolvePreview AutoResolvePreview => autoResolvePreview;
        public MemoriTooltipTrigger AutoResolveTooltip => autoResolveTooltip;
        public MemoriTooltipTrigger FightTooltip => fightTooltip;
        public Sprite DamageIcon => damageIcon;
        private Vector2 Rest => cardRest + new Vector2(0f, cardLift);

        public enum RewardIcon { Gold, Recruit, Ransom, Conscript, RaiseDead, Consume, Purge, HourOfDestiny }

        public Sprite Icon(RewardIcon kind) => kind switch
        {
            RewardIcon.Recruit => recruitIcon,
            RewardIcon.Ransom => ransomIcon,
            RewardIcon.Conscript => conscriptIcon,
            RewardIcon.RaiseDead => raiseDeadIcon,
            RewardIcon.Consume => consumeIcon,
            RewardIcon.Purge => purgeIcon,
            RewardIcon.HourOfDestiny => hourOfDestinyIcon,
            _ => goldIcon,
        };

        private void Awake()
        {
            cardRest = card.anchoredPosition;
        }

        private void LateUpdate() => FitCard();

        // A card too tall for the room above the army bar first rises toward the top bar, then shrinks only by what is still missing.
        private void FitCard()
        {
            Vector2 area = ((RectTransform)card.parent).rect.size;
            Vector2 size = card.rect.size;
            var key = new Vector3(area.x, area.y, size.y);
            if (key == fittedFor || size.y <= 0f) return;
            fittedFor = key;
            float restTop = area.y * card.anchorMin.y + cardRest.y;
            float maxLift = Mathf.Max(0f, area.y - topClearance - restTop);
            float lift = Mathf.Clamp(size.y + bottomClearance - restTop, 0f, maxLift);
            float room = restTop + lift - bottomClearance;
            float scale = Mathf.Clamp(Mathf.Min(room / size.y, area.x / size.x), minFitScale, 1f);
            card.anchoredPosition += new Vector2(0f, lift - cardLift);
            cardLift = lift;
            card.localScale = new Vector3(scale, scale, 1f);
        }

        // How long the card takes to land, so the enemy cards and the result wait for it.
        public float OpenSeconds => slideDelaySeconds + slideSeconds;
        public float CloseSeconds => closeSeconds;

        // The card drops in from above like the old panel (Feel's EaseInBounce lands and wobbles). It leaves upward on an
        // ease-in: the old curve reaches the top in about 0.1 s, which read as vanishing rather than sliding.
        public void PlayOpen() => Slide(slideDistance, 0f, slideDelaySeconds, slideSeconds, MMTween.MMTweenCurve.EaseInBounce);
        public void PlayClose() => Slide(0f, slideDistance, 0f, closeSeconds, MMTween.MMTweenCurve.EaseInCubic);

        private void Slide(float from, float to, float delay, float seconds, MMTween.MMTweenCurve curve)
        {
            if (rise != null) StopCoroutine(rise);
            rise = null;
            if (!isActiveAndEnabled)
            {
                card.anchoredPosition = Rest + new Vector2(0f, to);
                return;
            }
            rise = StartCoroutine(SlideCard(from, to, delay, seconds, curve));
        }

        private IEnumerator SlideCard(float from, float to, float delay, float seconds, MMTween.MMTweenCurve curve)
        {
            card.anchoredPosition = Rest + new Vector2(0f, from);
            if (delay > 0f) yield return new WaitForSecondsRealtime(delay);
            for (float t = 0f; t < seconds; t += Time.unscaledDeltaTime)
            {
                float k = MMTween.Evaluate(t / seconds, curve);
                card.anchoredPosition = Rest + new Vector2(0f, Mathf.LerpUnclamped(from, to, k));
                yield return null;
            }
            card.anchoredPosition = Rest + new Vector2(0f, to);
            rise = null;
        }

        #region Result pop-up
        // Greys the card under the old end-of-battle banner, which sits above the card; onGone swaps the card to the result
        // while the cover still hides it, and the banner lingers over the new result before it fades.
        public void PlayResultPopup(string title, string outcome, Action onGone)
        {
            HideResultPopup();
            // Set here, not in the prefab: a canvas saved without a parent canvas drops its sorting override.
            resultOverlay.overrideSorting = true;
            resultOverlay.sortingOrder = overlaySortingOrder;
            if (!isActiveAndEnabled)
            {
                onGone();
                return;
            }
            popup = StartCoroutine(ResultPopup(title, outcome, onGone));
        }

        public void HideResultPopup()
        {
            if (popup != null) StopCoroutine(popup);
            popup = null;
            endBattlePopup.gameObject.SetActive(false);
            resultCover.gameObject.SetActive(false);
        }

        private IEnumerator ResultPopup(string title, string outcome, Action onGone)
        {
            resultCover.gameObject.SetActive(true);
            if (!showBattleBanner)
            {
                // No banner: the card greys briefly, swaps to the result under the cover, and the cover lifts.
                for (float t = 0f; t < coverInSeconds; t += Time.unscaledDeltaTime)
                {
                    SetCover(1f - Mathf.Pow(1f - t / coverInSeconds, 3f));
                    yield return null;
                }
                SetCover(1f);
                onGone();
                for (float t = 0f; t < revealSeconds; t += Time.unscaledDeltaTime)
                {
                    SetCover(1f - t / revealSeconds);
                    yield return null;
                }
                resultCover.gameObject.SetActive(false);
                popup = null;
                yield break;
            }
            // Enabling the banner restarts its In clip; the texts are set after so nothing on enable overwrites them.
            endBattlePopup.gameObject.SetActive(true);
            endBattlePopup.SetBool(ActiveParameter, true);
            // The banner's content starts hidden; the old panel switched it on the same way. It never takes clicks.
            endBattleContent.CGEnable();
            CanvasGroup bannerGroup = endBattleContent.GetComponent<CanvasGroup>();
            bannerGroup.interactable = false;
            bannerGroup.blocksRaycasts = false;
            endBattleTitle.text = title;
            endBattleOutcome.text = outcome;
            for (float t = 0f; t < coverInSeconds; t += Time.unscaledDeltaTime)
            {
                SetCover(1f - Mathf.Pow(1f - t / coverInSeconds, 3f));
                yield return null;
            }
            SetCover(1f);

            // A second over the greyed card, then the result shows; the banner stays above it a while, then fades.
            yield return new WaitForSecondsRealtime(bannerHoldSeconds - coverInSeconds);
            onGone();
            // The cover lifts slowly, so the report and spoils fade in rather than snap in.
            for (float t = 0f; t < revealSeconds; t += Time.unscaledDeltaTime)
            {
                SetCover(1f - t / revealSeconds);
                yield return null;
            }
            resultCover.gameObject.SetActive(false);

            yield return new WaitForSecondsRealtime(bannerLingerSeconds);
            endBattleContent.FadeOutAsync(bannerFadeSeconds);
            yield return new WaitForSecondsRealtime(bannerFadeSeconds);
            endBattlePopup.gameObject.SetActive(false);
            popup = null;
        }

        private void SetCover(float k)
        {
            Color colour = resultCover.color;
            colour.a = coverAlpha * k;
            resultCover.color = colour;
        }
        #endregion

        #region Header
        public enum HeaderKind { Skirmish, Horde, Garrison, Victory, Defeat }

        public void SetHeader(HeaderKind kind, string title, string subtitle, Color wash)
        {
            headerIcon.sprite = kind switch
            {
                HeaderKind.Horde => hordeIcon,
                HeaderKind.Garrison => garrisonIcon,
                HeaderKind.Victory => victoryIcon,
                HeaderKind.Defeat => defeatIcon,
                _ => skirmishIcon,
            };
            headerTitle.text = title;
            // No subtitle lets the title centre in the header.
            headerSubtitle.gameObject.SetActive(!string.IsNullOrEmpty(subtitle));
            headerSubtitle.text = subtitle;
            wash.a = bandAlpha;
            headerBand.color = wash;
        }

        public void SetPill(string text, Color colour, TooltipContent tooltip = null)
        {
            pill.SetActive(!string.IsNullOrEmpty(text));
            pillText.text = text;
            pillText.color = colour;
            // Null on a panel prefab built before the pill had a tooltip.
            if (pillTooltip == null) return;
            pillTooltip.enabled = tooltip != null;
            if (tooltip != null) pillTooltip.SetUpToolTip(tooltip);
        }
        #endregion

        #region Before the battle
        public void ShowBeforeBattle()
        {
            preBattleBody.SetActive(true);
            resultBody.SetActive(false);
            SetPill(null, Color.clear);
            PlaceEnemyArmy(false, 0);
        }

        public void SetBattlefield(string value, Biome biome, bool garrison)
        {
            battlefieldValue.text = value;
            battlefieldIcon.sprite = garrison ? garrisonIcon : biome switch
            {
                Biome.Forest => forestIcon,
                Biome.River => riverIcon,
                Biome.Swamp => swampIcon,
                _ => plainsIcon,
            };
        }

        public void SetWeather(string value, Weather weather, string tooltipTitle, string tooltipBody)
        {
            weatherValue.text = value;
            weatherIcon.sprite = weather switch
            {
                Weather.Rain => rainIcon,
                Weather.Fog => fogIcon,
                Weather.Snow => snowIcon,
                _ => clearIcon,
            };
            weatherIcon.color = weather == Weather.ClearSkies ? sunTint : weatherTint;
            bool hasTooltip = !string.IsNullOrEmpty(tooltipBody);
            weatherTooltip.enabled = hasTooltip;
            if (hasTooltip) weatherTooltip.SetUpToolTip(tooltipTitle, tooltipBody);
        }

        // Cycles the value while a reroll spins; the icon follows the final weather.
        public void SetWeatherText(string value) => weatherValue.text = value;

        public void ShowHeavensong(bool show, string tooltipTitle = null, string tooltipBody = null)
        {
            heavensongGroup.SetActive(show);
            if (show) heavensongTooltip.SetUpToolTip(tooltipTitle, tooltipBody);
        }

        // The War Chest row: the line names the Twist and its price, and the button dims when the gold is short.
        public void ShowWarChest(bool show, string note = null, bool affordable = true, string tooltipTitle = null, string tooltipBody = null)
        {
            // Null on a panel prefab built before the War Chest row existed.
            if (warChestGroup == null) return;
            warChestGroup.SetActive(show);
            if (!show) return;
            warChestNote.text = note;
            warChestButton.interactable = affordable;
            warChestTooltip.SetUpToolTip(tooltipTitle, tooltipBody);
        }

        public void ShowReserveWarning(bool show) => reserveWarning.SetActive(show);

        // Godking has no Autoresolve: the button gives way to a plain line.
        public void SetAutoResolveAvailable(bool available)
        {
            autoResolveButton.gameObject.SetActive(available);
            autoResolveDisabled.SetActive(!available);
        }

        public void SetPrediction(string text) => autoResolvePrediction.text = text;

        public void SetBattleButtonsInteractable(bool interactable)
        {
            autoResolveButton.interactable = interactable;
            fightButton.interactable = interactable;
            autoResolveTooltip.enabled = interactable;
            fightTooltip.enabled = interactable;
        }
        #endregion

        #region After the battle
        // The enemy count comes from the panel: cards destroyed this frame still count as children until the frame ends.
        public void ShowResult(bool withSpoils, string outcome, int enemyCount)
        {
            preBattleBody.SetActive(false);
            resultBody.SetActive(true);
            stacks.SetActive(withSpoils);
            outcomeLine.gameObject.SetActive(!string.IsNullOrEmpty(outcome));
            outcomeLine.text = outcome;
            PlaceEnemyArmy(true, enemyCount);
        }

        public void SetReport(IReadOnlyList<(string label, string value)> cells)
        {
            for (int i = 0; i < reportLabels.Length; i++)
            {
                bool used = i < cells.Count;
                reportLabels[i].transform.parent.gameObject.SetActive(used);
                if (!used) continue;
                reportLabels[i].text = cells[i].label;
                reportValues[i].text = cells[i].value;
            }
        }

        public void SetDetailedStats(Func<TooltipContent> provider)
        {
            detailedStats.gameObject.SetActive(provider != null);
            if (provider != null) detailedStats.SetContentProvider(provider);
        }

        public void ClearRows()
        {
            foreach (EngagementSpoilRow row in spoilRows)
                if (row != null) Destroy(row.gameObject);
            foreach (EngagementChoiceRow row in choiceRows)
                if (row != null) Destroy(row.transform.parent.gameObject);
            spoilRows.Clear();
            choiceRows.Clear();
            noChoices.SetActive(false);
        }

        public EngagementSpoilRow AddSpoil()
        {
            EngagementSpoilRow row = Instantiate(spoilRowPrefab, spoilsParent);
            spoilRows.Add(row);
            return row;
        }

        public EngagementChoiceRow AddChoice()
        {
            EngagementChoiceRow row = Instantiate(choiceRowPrefab.transform.parent.gameObject, choicesParent).GetComponentInChildren<EngagementChoiceRow>(true);
            row.SetUp(OnChoiceHover);
            choiceRows.Add(row);
            return row;
        }

        // No Quarter can leave nothing to choose; a line says so instead of an empty column.
        public void ShowNoChoices(bool show) => noChoices.SetActive(show);

        // A March win pays nothing, so both stacks go and the report stands alone.
        public void ShowStacks(bool show) => stacks.SetActive(show);

        private void OnChoiceHover(EngagementChoiceRow hovered, bool isHovered)
        {
            foreach (EngagementChoiceRow row in choiceRows)
            {
                if (row == null || row.Current == EngagementChoiceRow.State.Chosen || !row.Button.interactable) continue;
                row.SetState(!isHovered ? EngagementChoiceRow.State.Rest : row == hovered ? EngagementChoiceRow.State.Hover : EngagementChoiceRow.State.Dim);
            }
        }

        public void ChooseRow(EngagementChoiceRow chosen, bool quiet = false)
        {
            if (!quiet) IAudioRequester.Instance.PlaySFX(chooseSfx);
            foreach (EngagementChoiceRow row in choiceRows)
            {
                if (row == chosen) row.SetState(EngagementChoiceRow.State.Chosen);
                else row.PopAway();
            }
        }
        #endregion

        // The same grid holds the enemy cards before and after the battle, so HUDPanel still reads their parent as the enemy.
        private void PlaceEnemyArmy(bool fallen, int count)
        {
            enemyArmyParent.SetParent(fallen ? fallenSlot : enemyArmySlot, false);
            enemyArmyParent.anchorMin = enemyArmyParent.anchorMax = enemyArmyParent.pivot = new Vector2(0.5f, 0.5f);
            enemyArmyParent.anchoredPosition = Vector2.zero;
            enemyArmyParent.localScale = Vector3.one * (fallen ? FallenScale : 1f);
            CanvasGroup dim = enemyArmyParent.GetComponent<CanvasGroup>();
            dim.alpha = fallen ? 0.55f : 1f;
            if (!fallen) return;
            // The slot sizes to the half-size strip so the report cells take the rest of the row.
            float width = Mathf.Max(1, count) * CardPitch * FallenScale + 2f * WellPadding;
            LayoutElement element = fallenSlot.GetComponent<LayoutElement>();
            element.minWidth = element.preferredWidth = width;
            element.minHeight = element.preferredHeight = CardHeight * FallenScale + 2f * WellPadding;
        }
    }
}
