using System.Collections.Generic;
using Memori.Audio;
using Memori.Localization;
using Memori.Tooltip;
using Memori.UI;
using TJ.Spells;
using TMPro;
using UnityEngine;
using UnityEngine.UI;

namespace TJ.MainMenu
{
    /// <summary>
    /// The hero screen of run setup, generated by RunSetupBuilder: the roster, the hero panel and the split bottom bars.
    /// Shows state only; PlayPanel owns the hero, the rules and the buttons' actions.
    /// </summary>
    public class CommanderScreenView : MonoBehaviour
    {
        [Header("Roster")]
        [SerializeField] private HeroRosterTile[] tiles;
        [SerializeField] private TMP_Text[] factionNames;
        [SerializeField] private Image[] factionPips;
        [SerializeField] private TMP_Text comingSoonText;

        [Header("Hero")]
        [SerializeField] private TMP_Text heroNameText;
        [SerializeField] private MemoriTooltipTrigger storyTrigger;
        [SerializeField] private Image heroFactionPip;
        [SerializeField] private TMP_Text heroFactionText;
        [SerializeField] private TMP_Text heroRegionText;
        [SerializeField] private TMP_Text loreText;
        [SerializeField] private ScrollRect loreScroll;

        [Header("Effects")]
        [SerializeField] private TMP_Text[] heroEffectTitles;
        [SerializeField] private TMP_Text[] heroEffectBodies;
        [SerializeField] private GameObject[] heroEffectRows;
        [SerializeField] private Image factionEffectsPip;
        [SerializeField] private TMP_Text campaignTitle;
        [SerializeField] private TMP_Text campaignBody;
        [SerializeField] private TMP_Text battleTitle;
        [SerializeField] private TMP_Text battleBody;

        [Header("Signature")]
        [SerializeField] private Image unitPortrait;
        [SerializeField] private Image unitFrame;
        [SerializeField] private TMP_Text unitNameText;
        [SerializeField] private TroopHoverPlayPanel unitHover;
        [SerializeField] private GameObject spellCard;
        [SerializeField] private Image spellIcon;
        [SerializeField] private Image spellFrame;
        [SerializeField] private Image spellWash;
        [SerializeField] private TMP_Text spellNameText;
        [SerializeField] private MemoriTooltipTrigger spellTooltip;

        [Header("Record")]
        [SerializeField] private TMP_Text recordTitle;
        [SerializeField] private CanvasGroup[] recordCrests;
        [SerializeField] private TMP_Text[] recordLevelNames;
        [SerializeField] private TMP_Text[] recordStates;
        [SerializeField] private float unwonCrestAlpha = 0.3f;

        [Header("Bars")]
        [SerializeField] private Button returnButton;
        [SerializeField] private Button buildArmyButton;
        [SerializeField] private TMP_Text treasuryText;

        public HeroRosterTile[] Tiles => tiles;
        public Button ReturnButton => returnButton;
        public Button BuildArmyButton => buildArmyButton;

        /// <summary>Fills the roster. Heroes arrive in roster order, two per faction card.</summary>
        public int LoadRoster(Hero[] heroes, PlayPanel playPanel)
        {
            int count = Mathf.Min(tiles.Length, heroes.Length);
            for (int i = 0; i < tiles.Length; i++)
            {
                tiles[i].gameObject.SetActive(i < count);
                if (i < count) tiles[i].Load(heroes[i], playPanel);
            }
            for (int card = 0; card < factionNames.Length; card++)
            {
                int first = card * 2;
                bool shown = first < count;
                factionNames[card].transform.parent.parent.gameObject.SetActive(shown);
                if (!shown) continue;
                Race race = heroes[first].Race;
                factionNames[card].text = T(race.ToString());
                factionPips[card].color = ColorData.GetRaceDisplayColor(race);
            }
            comingSoonText.text = string.Format(T("heroSelectComingSoon"), T("OlympianPhalanx"));
            return count;
        }

        /// <summary>Shows the picked hero on the hero panel. It only writes, never adds.</summary>
        public void ShowHero(Hero hero, PlayPanel playPanel)
        {
            string heroName = T(hero.HeroName);
            Color raceColour = ColorData.GetRaceDisplayColor(hero.Race);
            heroNameText.text = heroName;
            storyTrigger.SetUpToolTip(heroName, T(hero.HeroDescription));
            heroFactionPip.color = raceColour;
            heroFactionText.text = T(hero.Race.ToString());
            heroFactionText.color = raceColour;
            heroRegionText.text = T(hero.Race + "MapRegion");
            loreText.text = LocalizationManager.Instance.GetLoreString(hero.HeroPrefabName) ?? string.Empty;
            // Each hero's story starts at the top, not where the previous one was scrolled to.
            loreScroll.StopMovement();
            loreScroll.content.anchoredPosition = Vector2.zero;

            for (int i = 0; i < heroEffectRows.Length; i++)
            {
                HeroBonusText.GetParts(hero, i, out string title, out string body);
                bool shown = !string.IsNullOrEmpty(title) || !string.IsNullOrEmpty(body);
                heroEffectRows[i].SetActive(shown);
                if (!shown) continue;
                heroEffectTitles[i].text = title;
                KeywordText.Apply(heroEffectBodies[i], body);
            }

            factionEffectsPip.color = raceColour;
            SplitNamed(T(hero.Race + "BonusDescription"), out string campaignName, out string campaignText);
            campaignTitle.text = campaignName;
            KeywordText.Apply(campaignBody, campaignText);
            battleTitle.text = T(hero.Race + "PassiveName");
            KeywordText.Apply(battleBody, RacePassiveInfo.GetDescription(hero.Race));

            ShowSignature(hero, playPanel);
            ShowRecord(hero, heroName);
        }

        public void ShowTreasury(int total, int baseGold, int renownBonus)
        {
            if (treasuryCount != null) { StopCoroutine(treasuryCount); treasuryCount = null; }
            previousTotal = shownTotal < 0 ? total : shownTotal;
            shownTotal = total;
            shownBase = baseGold;
            shownRenown = renownBonus;
            treasuryText.text = TreasuryText(total);
        }

        // Counts from the last hero's treasury to this one's, with a few coin ticks.
        public void CountTreasury()
        {
            if (!isActiveAndEnabled || previousTotal == shownTotal) return;
            if (treasuryCount != null) StopCoroutine(treasuryCount);
            treasuryCount = StartCoroutine(UIJuice.CountTo(treasuryText, previousTotal, shownTotal, 0.3f, TreasuryText,
                () => IAudioRequester.Instance.PlaySFX(SFXData.CoinClink)));
        }

        private int shownTotal = -1, previousTotal, shownBase, shownRenown;
        private Coroutine treasuryCount;

        private string TreasuryText(int total)
        {
            string label = $"<color={ColorData.Secondary}><size=75%>{T("Treasury")}</size></color>  ";
            string amount = $"<b><color={ColorData.Gold}><size=125%>{total}</size></color></b> <sprite name=GoldSprite>";
            string breakdown = shownRenown > 0
                ? $"\n<color={ColorData.Secondary}><size=80%>{string.Format(T("heroTreasuryBreakdown"), shownBase, $"<color={ColorData.Green}>+{shownRenown}</color>")}</size></color>"
                : "";
            return label + amount + breakdown;
        }

        #region Arrival
        private const float RevealTime = 0.2f, PairGap = 0.04f, BlockGap = 0.045f;
        private Coroutine arrival, heroReveal;

        // The roster deals in two tiles at a time, faction by faction, then the hero panel's blocks follow.
        public void PlayArrival(float delay)
        {
            if (!isActiveAndEnabled) return;
            if (arrival != null) StopCoroutine(arrival);
            var items = new List<RectTransform>();
            var delays = new List<float>();
            for (int i = 0; i < tiles.Length; i++)
            {
                if (!tiles[i].gameObject.activeSelf) continue;
                items.Add((RectTransform)tiles[i].transform);
                delays.Add(delay + (i / 2) * PairGap);
            }
            AddPanelBlocks(items, delays, delay + 0.08f);
            arrival = StartCoroutine(UIJuice.Reveal(items, delays, RevealTime));
        }

        // A new pick re-deals the hero panel top to bottom, so the eye reads that everything on it changed.
        public void RevealHero()
        {
            if (!isActiveAndEnabled) return;
            if (heroReveal != null) StopCoroutine(heroReveal);
            var items = new List<RectTransform>();
            var delays = new List<float>();
            AddPanelBlocks(items, delays, 0.03f);
            heroReveal = StartCoroutine(UIJuice.Reveal(items, delays, 0.18f));
        }

        // Every child of the hero panel, grouped into blocks that start at the name row and at each section heading.
        private void AddPanelBlocks(List<RectTransform> items, List<float> delays, float start)
        {
            Transform panel = transform.Find(HeroPanelName);
            if (panel == null) { Debug.LogError($"[CommanderScreenView] No '{HeroPanelName}' to reveal."); return; }
            int block = 0;
            for (int i = 0; i < panel.childCount; i++)
            {
                var child = (RectTransform)panel.GetChild(i);
                if (!child.gameObject.activeSelf) continue;
                LayoutElement layout = child.GetComponent<LayoutElement>();
                if (layout != null && layout.ignoreLayout) continue;
                if (child.name.StartsWith("Heading ")) block++;
                items.Add(child);
                delays.Add(start + block * BlockGap);
            }
        }

        private const string HeroPanelName = "Hero Panel";
        #endregion

        private void ShowSignature(Hero hero, PlayPanel playPanel)
        {
            UnitName unit = hero.SignatureUnit;
            unitPortrait.sprite = TabletopTavernData.Instance.GetUnitIcon(unit);
            unitFrame.color = (Color)ColorData.GetRarityTierColor(TabletopTavernData.Instance.GetSquadStats(unit).RarityTier);
            unitNameText.text = T(unit.ToString());
            unitHover.SetUp(PlayPanel.SIGNATURE_UNIT_HOVER_INDEX, playPanel);

            SpellData spell = null;
#if SPELLS
            spell = SpellRegistry.Get(hero.SignatureSpell);
#endif
            spellCard.SetActive(spell != null);
            if (spell == null) return;
            Color colour = ColorData.GetRaceDisplayColor(spell.Race);
            spellIcon.sprite = spell.SpellSprite;
            spellIcon.color = colour;
            spellFrame.color = colour;
            spellWash.color = new Color(colour.r, colour.g, colour.b, spellWash.color.a);
            spellNameText.text = T(spell.Spell.ToString());
            spellTooltip.SetContentProvider(() => SpellTooltip.Build(spell, new SpellTooltip.Context { Pinned = true }));
        }

        private void ShowRecord(Hero hero, string heroName)
        {
            recordTitle.text = string.Format(T("heroRecordTitle"), heroName);
            bool[] won = DifficultyMetal.WonLevels(hero.HeroID);
            for (int i = 0; i < recordCrests.Length && i < DifficultyRules.Ladder.Length; i++)
            {
                bool levelWon = i < won.Length && won[i];
                recordCrests[i].alpha = levelWon ? 1f : unwonCrestAlpha;
                recordLevelNames[i].text = T(DifficultyData.GetDifficultyLevelData(DifficultyRules.Ladder[i]).difficultyName);
                recordLevelNames[i].color = levelWon ? DifficultyMetal.ForRank(i) : DifficultyMetal.PlainFrame;
                recordStates[i].text = T(levelWon ? "heroRecordWon" : "heroRecordNotYet");
                recordStates[i].color = levelWon ? (Color)ColorData.HexToRgba(ColorData.Positive) : DifficultyMetal.PlainFrame;
            }
        }

        // "Imperial Edict: First recruitment pack is free" splits at the first colon into the effect's name and its text.
        private static void SplitNamed(string text, out string name, out string body)
        {
            int colon = text.IndexOf(':');
            name = colon < 0 ? string.Empty : text[..colon].Trim();
            body = colon < 0 ? text : text[(colon + 1)..].Trim();
        }

        private static string T(string key) => LocalizationManager.Instance.GetText(key);
    }
}
