using Memori.Localization;
using Memori.Tooltip;
using TJ.Spells;
using TMPro;
using UnityEngine;
using UnityEngine.UI;

namespace TJ.MainMenu
{
    /// <summary>
    /// The hero screen of run setup, generated by RunSetupBuilder: the roster, the hero panel and the split bottom bars.
    /// Shows state only; PlayPanel owns the hero, the rules and the buttons' actions.
    /// </summary>
    public class CommanderScreenView : MonoBehaviour
    {
        [Header("Roster")]
        [SerializeField] private HeroRosterTile[] tiles;
        [SerializeField] private TMP_Text[] factionNames;
        [SerializeField] private Image[] factionPips;
        [SerializeField] private TMP_Text rosterCountText;
        [SerializeField] private TMP_Text comingSoonText;

        [Header("Hero")]
        [SerializeField] private TMP_Text heroNameText;
        [SerializeField] private MemoriTooltipTrigger storyTrigger;
        [SerializeField] private Image heroFactionPip;
        [SerializeField] private TMP_Text heroFactionText;
        [SerializeField] private TMP_Text heroRegionText;
        [SerializeField] private TMP_Text loreText;
        [SerializeField] private ScrollRect loreScroll;

        [Header("Effects")]
        [SerializeField] private TMP_Text[] heroEffectTitles;
        [SerializeField] private TMP_Text[] heroEffectBodies;
        [SerializeField] private GameObject[] heroEffectRows;
        [SerializeField] private Image factionEffectsPip;
        [SerializeField] private TMP_Text campaignTitle;
        [SerializeField] private TMP_Text campaignBody;
        [SerializeField] private TMP_Text battleTitle;
        [SerializeField] private TMP_Text battleBody;

        [Header("Signature")]
        [SerializeField] private Image unitPortrait;
        [SerializeField] private Image unitFrame;
        [SerializeField] private TMP_Text unitNameText;
        [SerializeField] private TroopHoverPlayPanel unitHover;
        [SerializeField] private GameObject spellCard;
        [SerializeField] private Image spellIcon;
        [SerializeField] private Image spellFrame;
        [SerializeField] private Image spellWash;
        [SerializeField] private TMP_Text spellNameText;
        [SerializeField] private MemoriTooltipTrigger spellTooltip;

        [Header("Record")]
        [SerializeField] private TMP_Text recordTitle;
        [SerializeField] private CanvasGroup[] recordCrests;
        [SerializeField] private TMP_Text[] recordLevelNames;
        [SerializeField] private TMP_Text[] recordStates;
        [SerializeField] private float unwonCrestAlpha = 0.3f;

        [Header("Bars")]
        [SerializeField] private Button returnButton;
        [SerializeField] private Button buildArmyButton;
        [SerializeField] private TMP_Text treasuryText;

        public HeroRosterTile[] Tiles => tiles;
        public Button ReturnButton => returnButton;
        public Button BuildArmyButton => buildArmyButton;

        /// <summary>Fills the roster. Heroes arrive in roster order, two per faction card.</summary>
        public int LoadRoster(Hero[] heroes, PlayPanel playPanel)
        {
            int count = Mathf.Min(tiles.Length, heroes.Length);
            for (int i = 0; i < tiles.Length; i++)
            {
                tiles[i].gameObject.SetActive(i < count);
                if (i < count) tiles[i].Load(heroes[i], playPanel);
            }
            int factions = 0;
            for (int card = 0; card < factionNames.Length; card++)
            {
                int first = card * 2;
                bool shown = first < count;
                factionNames[card].transform.parent.parent.gameObject.SetActive(shown);
                if (!shown) continue;
                factions++;
                Race race = heroes[first].Race;
                factionNames[card].text = T(race.ToString());
                factionPips[card].color = ColorData.GetRaceDisplayColor(race);
            }
            rosterCountText.text = string.Format(T("heroSelectCount"), count, factions);
            comingSoonText.text = string.Format(T("heroSelectComingSoon"), T("OlympianPhalanx"));
            return count;
        }

        /// <summary>Shows a hero on the hero panel. Runs on every roster hover, so it only writes, never adds.</summary>
        public void ShowHero(Hero hero, PlayPanel playPanel)
        {
            string heroName = T(hero.HeroName);
            Color raceColour = ColorData.GetRaceDisplayColor(hero.Race);
            heroNameText.text = heroName;
            storyTrigger.SetUpToolTip(heroName, T(hero.HeroDescription));
            heroFactionPip.color = raceColour;
            heroFactionText.text = T(hero.Race.ToString());
            heroFactionText.color = raceColour;
            heroRegionText.text = "· " + T(hero.Race + "MapRegion");
            loreText.text = LocalizationManager.Instance.GetLoreString(hero.HeroPrefabName) ?? string.Empty;
            // Each hero's story starts at the top, not where the previous one was scrolled to.
            loreScroll.StopMovement();
            loreScroll.content.anchoredPosition = Vector2.zero;

            for (int i = 0; i < heroEffectRows.Length; i++)
            {
                HeroBonusText.GetParts(hero, i, out string title, out string body);
                bool shown = !string.IsNullOrEmpty(title) || !string.IsNullOrEmpty(body);
                heroEffectRows[i].SetActive(shown);
                if (!shown) continue;
                heroEffectTitles[i].text = title;
                KeywordText.Apply(heroEffectBodies[i], body);
            }

            factionEffectsPip.color = raceColour;
            SplitNamed(T(hero.Race + "BonusDescription"), out string campaignName, out string campaignText);
            campaignTitle.text = campaignName;
            KeywordText.Apply(campaignBody, campaignText);
            battleTitle.text = T(hero.Race + "PassiveName");
            KeywordText.Apply(battleBody, RacePassiveInfo.GetDescription(hero.Race));

            ShowSignature(hero, playPanel);
            ShowRecord(hero, heroName);
        }

        public void ShowTreasury(int total, int baseGold, int renownBonus)
        {
            string label = $"<color={ColorData.Secondary}><size=75%><uppercase>{T("Treasury")}</uppercase></size></color>  ";
            string amount = $"<b><color={ColorData.Gold}><size=125%>{total}</size></color></b> <sprite name=GoldSprite>";
            string breakdown = renownBonus > 0
                ? $"\n<color={ColorData.Secondary}><size=80%>{string.Format(T("heroTreasuryBreakdown"), baseGold, $"<color={ColorData.Green}>+{renownBonus}</color>")}</size></color>"
                : "";
            treasuryText.text = label + amount + breakdown;
        }

        private void ShowSignature(Hero hero, PlayPanel playPanel)
        {
            UnitName unit = hero.SignatureUnit;
            unitPortrait.sprite = TabletopTavernData.Instance.GetUnitIcon(unit);
            unitFrame.color = (Color)ColorData.GetRarityTierColor(TabletopTavernData.Instance.GetSquadStats(unit).RarityTier);
            unitNameText.text = T(unit.ToString());
            unitHover.SetUp(PlayPanel.SIGNATURE_UNIT_HOVER_INDEX, playPanel);

            SpellData spell = null;
#if SPELLS
            spell = SpellRegistry.Get(hero.SignatureSpell);
#endif
            spellCard.SetActive(spell != null);
            if (spell == null) return;
            Color colour = ColorData.GetRaceDisplayColor(spell.Race);
            spellIcon.sprite = spell.SpellSprite;
            spellIcon.color = colour;
            spellFrame.color = colour;
            spellWash.color = new Color(colour.r, colour.g, colour.b, spellWash.color.a);
            spellNameText.text = T(spell.Spell.ToString());
            spellTooltip.SetContentProvider(() => SpellTooltip.Build(spell, new SpellTooltip.Context { Pinned = true }));
        }

        private void ShowRecord(Hero hero, string heroName)
        {
            recordTitle.text = string.Format(T("heroRecordTitle"), heroName);
            bool[] won = DifficultyMetal.WonLevels(hero.HeroID);
            for (int i = 0; i < recordCrests.Length && i < DifficultyRules.Ladder.Length; i++)
            {
                bool levelWon = i < won.Length && won[i];
                recordCrests[i].alpha = levelWon ? 1f : unwonCrestAlpha;
                recordLevelNames[i].text = T(DifficultyData.GetDifficultyLevelData(DifficultyRules.Ladder[i]).difficultyName);
                recordLevelNames[i].color = levelWon ? DifficultyMetal.ForRank(i) : DifficultyMetal.PlainFrame;
                recordStates[i].text = T(levelWon ? "heroRecordWon" : "heroRecordNotYet");
                recordStates[i].color = levelWon ? (Color)ColorData.HexToRgba(ColorData.Positive) : DifficultyMetal.PlainFrame;
            }
        }

        // "Imperial Edict: First recruitment pack is free" splits at the first colon into the effect's name and its text.
        private static void SplitNamed(string text, out string name, out string body)
        {
            int colon = text.IndexOf(':');
            name = colon < 0 ? string.Empty : text[..colon].Trim();
            body = colon < 0 ? text : text[(colon + 1)..].Trim();
        }

        private static string T(string key) => LocalizationManager.Instance.GetText(key);
    }
}
