using UnityEngine;
using UnityEngine.UI;

namespace TJ.MainMenu
{
    /// <summary>The warband screen's build panel and bars, generated by RunSetupBuilder. Shows the hero's won levels beside Difficulty.</summary>
    public class WarbandBuildView : MonoBehaviour
    {
        [SerializeField] private Image[] wonGems;

        public void ShowRecord(int heroID)
        {
            bool[] won = DifficultyMetal.WonLevels(heroID);
            for (int i = 0; i < wonGems.Length; i++)
                wonGems[i].color = i < won.Length && won[i] ? DifficultyMetal.ForRank(i) : DifficultyMetal.Unwon;
        }
    }
}
