using System.Collections.Generic;
using Memori.UI;
using UnityEngine;
using UnityEngine.UI;

namespace TJ.MainMenu
{
    /// <summary>The warband screen's build panel and bars, generated by RunSetupBuilder. Shows the hero's won levels beside Difficulty.</summary>
    public class WarbandBuildView : MonoBehaviour
    {
        [SerializeField] private Image[] wonGems;

        // The builder's block names, top to bottom.
        private static readonly string[] Blocks = { "Build Panel/Army", "Build Panel/Gear And Spells", "Build Panel/Difficulty" };
        private Coroutine arrival;

        // Shared with the recruit list, so both columns deal in their three blocks at the same pace.
        public const float ArrivalStep = 0.1f;
        public const float ArrivalTime = 0.3f;

        // The build blocks follow the screen in, one after another.
        public void PlayArrival()
        {
            if (!isActiveAndEnabled) return;
            var items = new List<RectTransform>();
            var delays = new List<float>();
            foreach (string path in Blocks)
            {
                Transform block = transform.Find(path);
                if (block == null) { Debug.LogError($"[WarbandBuildView] No '{path}' to reveal."); continue; }
                delays.Add(0.05f + items.Count * ArrivalStep);
                items.Add((RectTransform)block);
            }
            if (arrival != null) StopCoroutine(arrival);
            arrival = StartCoroutine(UIJuice.Reveal(items, delays, ArrivalTime));
        }

        public void ShowRecord(int heroID)
        {
            bool[] won = DifficultyMetal.WonLevels(heroID);
            for (int i = 0; i < wonGems.Length; i++)
                wonGems[i].color = i < won.Length && won[i] ? DifficultyMetal.ForRank(i) : DifficultyMetal.Unwon;
        }
    }
}
