using System.Collections;
using TMPro;
using UnityEngine;
using UnityEngine.UI;
using Memori.UI;

namespace TJ.Games
{
    /// <summary>
    /// The games panel's UI, generated by GamesPanelBuilder: the choosing card and the table strip under the dice.
    /// GamesPanel fills it; this class only shows what it is given.
    /// </summary>
    public class GamesPanelView : MonoBehaviour
    {
        // A click on a stake, Play or Buy a Round the player cannot afford shakes it; these buttons are switched off then.
        public void AttachDenyFeedback()
        {
            foreach (GamesStakeButton stake in stakeButtons) if (stake != null) UIDenyFeedback.Attach(stake.Button);
            UIDenyFeedback.Attach(playButton);
            UIDenyFeedback.Attach(buyButton);
        }

        public enum Table { Dice, HigherLower, Round }

        #region Card
        [SerializeField] private CanvasGroup card;
        [SerializeField] private TMP_Text stakesValue;
        [SerializeField] private CanvasGroup[] columns;
        [SerializeField] private TMP_Text diceStakeValue;
        [SerializeField] private TMP_Text diceBestValue;
        [SerializeField] private TMP_Text diceWinValue;
        [SerializeField] private GamesStakeButton[] stakeButtons;
        [SerializeField] private TMP_Text hiloStakeValue;
        [SerializeField] private TMP_Text hiloBestValue;
        [SerializeField] private TMP_Text hiloCallsValue;
        [SerializeField] private Button playButton;
        [SerializeField] private TMP_Text playAmount;
        [SerializeField] private TMP_Text roundCostValue;
        [SerializeField] private TMP_Text roundHealValue;
        [SerializeField] private TMP_Text roundHealLine;
        [SerializeField] private Button buyButton;
        [SerializeField] private TMP_Text buyAmount;
        [SerializeField] private Button skipButton;
        #endregion

        #region Strip
        [SerializeField] private CanvasGroup strip;
        [SerializeField] private Image stripIcon;
        [SerializeField] private Sprite[] tableIcons;
        [SerializeField] private TMP_Text stripTitle;
        [SerializeField] private TMP_Text stripSubtitle;
        [SerializeField] private TMP_Text stripCap;
        [SerializeField] private TMP_Text stripValue;
        [SerializeField] private GameObject payoutRow;
        [SerializeField] private CanvasGroup[] payoutCells;
        [SerializeField] private GameObject[] payoutLit;
        [SerializeField] private GameObject ladder;
        [SerializeField] private Image[] ladderFills;
        [SerializeField] private Image[] ladderBorders;
        [SerializeField] private Image[] ladderGlows;
        [SerializeField] private TMP_Text[] ladderLabels;
        [SerializeField] private TMP_Text[] ladderValues;
        [SerializeField] private Image[] ladderLinks;
        [SerializeField] private GameObject callRow;
        [SerializeField] private GamesCallButton higherButton;
        [SerializeField] private GamesCallButton lowerButton;
        [SerializeField] private Button cashOutButton;
        [SerializeField] private TMP_Text cashOutDetail;
        [SerializeField] private GameObject resultRow;
        [SerializeField] private GameObject readout;
        [SerializeField] private Image youFace;
        [SerializeField] private Image houseFace;
        // Faces 1-6 in order.
        [SerializeField] private Sprite[] dieFaces;
        [SerializeField] private Image youRing;
        [SerializeField] private Image houseRing;
        [SerializeField] private GameObject rewindHint;
        [SerializeField] private GameObject roundNote;
        [SerializeField] private TMP_Text roundNoteText;
        [SerializeField] private Button continueButton;
        #endregion

        #region Style
        [SerializeField] private Color reached = new(0.914f, 0.753f, 0.416f, 1f);
        [SerializeField] private Color reachedBorder = new(0.69f, 0.541f, 0.243f, 1f);
        [SerializeField] private Color empty = new(0.086f, 0.125f, 0.137f, 1f);
        [SerializeField] private Color emptyBorder = new(0.337f, 0.376f, 0.373f, 1f);
        [SerializeField] private Color labelCurrent = new(0.914f, 0.753f, 0.416f, 1f);
        [SerializeField] private Color labelReached = new(0.706f, 0.667f, 0.58f, 1f);
        [SerializeField] private Color labelEmpty = new(0.424f, 0.467f, 0.482f, 1f);
        [SerializeField] private Color valueReached = new(0.89f, 0.733f, 0.443f, 1f);
        [SerializeField] private Color valueEmpty = new(0.549f, 0.525f, 0.463f, 1f);
        [SerializeField] private Color cream = new(0.925f, 0.902f, 0.847f, 1f);
        [SerializeField] private Color tieLit = new(0.914f, 0.753f, 0.416f, 1f);
        [SerializeField] private Color houseGlow = new(0.925f, 0.902f, 0.847f, 1f);
        [SerializeField, Range(0f, 1f)] private float dimCellAlpha = 0.42f;
        [SerializeField] private float fadeSeconds = 0.2f;
        #endregion

        #region Placement
        // Canvas units from the canvas top; the strip hangs here, just under the dice, when it fits above the army bar.
        [SerializeField] private float stripTop = 520f;
        // The dice table with its result row is the tallest strip, so it decides whether the strip fits under the dice.
        [SerializeField] private float stripTallest = 272f;
        // The army bar's top edge sits this far above the canvas bottom at every UI Scale, plus a small gap.
        [SerializeField] private float armyBarClearance = 280f;
        // On a short canvas GamesPanel raises the dice, and the strip's bottom edge sits here, just above the army bar.
        [SerializeField] private float shortStripBottom = 545f;
        #endregion

        private float placedCanvasHeight;
        private Coroutine swap;
        private Coroutine[] columnFades;

        // Read live so Colorblind Mode's swap applies.
        private static Color Positive => (Color)ColorData.HexToRgba(ColorData.Positive);
        private static Color Negative => (Color)ColorData.HexToRgba(ColorData.Negative);

        // Payout rules in the strip's order: higher and six against one win, the tie pushes, lower loses.
        private static readonly int[] PayoutSide = { 1, 1, 0, -1 };

        public Button SkipButton => skipButton;
        public Button PlayButton => playButton;
        public Button BuyButton => buyButton;
        public GamesStakeButton[] StakeButtons => stakeButtons;
        public GamesCallButton HigherButton => higherButton;
        public GamesCallButton LowerButton => lowerButton;
        public Button CashOutButton => cashOutButton;
        public Button ContinueButton => continueButton;

        #region Card
        public void SetStakes(string text) => stakesValue.text = text;

        public void SetDiceColumn(string stakeRange, string best, string win, string[] amounts)
        {
            diceStakeValue.text = stakeRange;
            diceBestValue.text = best;
            diceWinValue.text = win;
            for (int i = 0; i < stakeButtons.Length && i < amounts.Length; i++) stakeButtons[i].SetAmount(amounts[i]);
        }

        public void SetHigherLowerColumn(string stake, string best, string calls, string amount)
        {
            hiloStakeValue.text = stake;
            hiloBestValue.text = best;
            hiloCallsValue.text = calls;
            playAmount.text = amount;
        }

        public void SetRoundColumn(string cost, string heal, string healLine, string amount)
        {
            roundCostValue.text = cost;
            roundHealValue.text = heal;
            roundHealLine.text = healLine;
            buyAmount.text = amount;
        }

        public void SetPlayAffordable(bool affordable) => SetAffordable(playButton, playAmount, affordable);

        public void SetBuyAffordable(bool affordable) => SetAffordable(buyButton, buyAmount, affordable);

        private void SetAffordable(Button button, TMP_Text amount, bool affordable)
        {
            button.interactable = affordable;
            amount.color = affordable ? cream : Negative;
        }

        // The card opens with its columns hidden and unclickable; GamesPanel reveals them one by one, then enables it.
        public void ShowChoosing(bool columnsShown)
        {
            StopAll();
            SetGroup(card, 1f, columnsShown);
            SetGroup(strip, 0f, false);
            foreach (CanvasGroup column in columns) column.alpha = columnsShown ? 1f : 0f;
        }

        public void SetCardInteractable(bool interactable)
        {
            card.interactable = interactable;
            card.blocksRaycasts = interactable;
        }

        public void RevealColumn(int index)
        {
            if (index < 0 || index >= columns.Length) return;
            columnFades ??= new Coroutine[columns.Length];
            if (columnFades[index] != null) StopCoroutine(columnFades[index]);
            columnFades[index] = isActiveAndEnabled ? StartCoroutine(Fade(columns[index], 1f)) : null;
            if (columnFades[index] == null) columns[index].alpha = 1f;
        }
        #endregion

        #region Strip
        // The card folds away and the strip takes its place under the dice.
        public void ShowTable(Table table, string title, bool animate)
        {
            StopAll();
            stripIcon.sprite = tableIcons[(int)table];
            stripTitle.text = title;
            payoutRow.SetActive(table == Table.Dice);
            ladder.SetActive(table == Table.HigherLower);
            callRow.SetActive(false);
            resultRow.SetActive(false);
            ShowPayout(-1);
            SetGroup(card, card.alpha, false);
            SetGroup(strip, strip.alpha, true);
            if (animate && isActiveAndEnabled && fadeSeconds > 0f)
            {
                swap = StartCoroutine(Swap());
                return;
            }
            card.alpha = 0f;
            strip.alpha = 1f;
        }

        public void SetStripText(string subtitle, string cap, string value)
        {
            stripSubtitle.text = subtitle;
            stripCap.text = cap;
            stripValue.text = value;
        }

        // Lights the payout rule that paid and dims the rest; -1 shows every rule plainly.
        public void ShowPayout(int lit)
        {
            for (int i = 0; i < payoutCells.Length; i++)
            {
                payoutCells[i].alpha = lit < 0 || i == lit ? 1f : dimCellAlpha;
                payoutLit[i].SetActive(i == lit);
            }
            if (lit >= 0 && lit < payoutLit.Length) TintLit(payoutLit[lit], PayoutSide[lit]);
        }

        // The lit rule's outline and wash keep the prefab's alpha; only the hue follows win, tie or loss.
        private void TintLit(GameObject lit, int side)
        {
            Color colour = side > 0 ? Positive : side < 0 ? Negative : tieLit;
            foreach (Image image in lit.GetComponentsInChildren<Image>(true))
            {
                colour.a = image.color.a;
                image.color = colour;
            }
        }

        public void SetLadderValues(string[] values)
        {
            for (int i = 0; i < ladderValues.Length && i < values.Length; i++) ladderValues[i].text = values[i];
        }

        // Steps up to and including step are reached; a bust turns the current step red.
        public void ShowLadder(int step, bool bust)
        {
            for (int i = 0; i < ladderFills.Length; i++)
            {
                bool isReached = i <= step;
                bool isCurrent = i == step;
                bool isBust = bust && isCurrent;
                Color negative = Negative;
                ladderFills[i].color = isBust ? negative : isReached ? reached : empty;
                ladderBorders[i].color = isBust ? negative : isReached ? reachedBorder : emptyBorder;
                ladderGlows[i].enabled = isCurrent;
                ladderGlows[i].color = new Color(isBust ? negative.r : reached.r, isBust ? negative.g : reached.g, isBust ? negative.b : reached.b, 0.22f);
                ladderLabels[i].color = isBust ? negative : isCurrent ? labelCurrent : isReached ? labelReached : labelEmpty;
                ladderValues[i].color = isBust ? negative : isReached ? valueReached : valueEmpty;
            }
            for (int i = 0; i < ladderLinks.Length; i++)
                ladderLinks[i].color = i < step ? reachedBorder : emptyBorder;
        }

        public void ShowCalls(string higherChance, int higherPercent, bool[] higherFaces, string lowerChance, int lowerPercent, bool[] lowerFaces, string cashOut, bool canCashOut)
        {
            callRow.SetActive(true);
            resultRow.SetActive(false);
            higherButton.Set(higherChance, higherPercent, higherFaces);
            lowerButton.Set(lowerChance, lowerPercent, lowerFaces);
            cashOutDetail.text = cashOut;
            higherButton.Button.interactable = higherPercent > 0;
            lowerButton.Button.interactable = lowerPercent > 0;
            cashOutButton.interactable = canCashOut;
        }

        // While a die is in the air the calls stay on screen but cannot be pressed.
        public void LockCalls()
        {
            higherButton.Button.interactable = false;
            lowerButton.Button.interactable = false;
            cashOutButton.interactable = false;
        }

        // A face of 0 hides the dice readout; result is +1 for a win ring, -1 for a loss ring, 0 for none.
        public void ShowResult(int you, int house, int youResult, int houseResult, bool offerRewind)
        {
            callRow.SetActive(false);
            resultRow.SetActive(true);
            readout.SetActive(you > 0 && house > 0);
            if (you > 0 && house > 0)
            {
                youFace.sprite = dieFaces[Mathf.Clamp(you, 1, 6) - 1];
                houseFace.sprite = dieFaces[Mathf.Clamp(house, 1, 6) - 1];
            }
            SetRing(youRing, youResult);
            // The house's glow never takes the win or loss colour, so green only ever means the player came out ahead.
            SetRing(houseRing, houseResult, houseGlow);
            rewindHint.SetActive(offerRewind);
            roundNote.SetActive(false);
            if (!isActiveAndEnabled) return;
            CanvasGroup group = resultRow.GetComponent<CanvasGroup>();
            if (group == null) group = resultRow.AddComponent<CanvasGroup>();
            StartCoroutine(UIJuice.Open(group, null, fadeSeconds, 0f));
            if (youResult > 0) StartCoroutine(UIJuice.Punch(youFace.transform.parent, 1.12f));
            else if (houseResult > 0) StartCoroutine(UIJuice.Punch(houseFace.transform.parent, 1.12f));
        }

        // A bought round has no dice; the heal line takes the readout's place.
        public void ShowRoundResult(string healLine)
        {
            ShowResult(0, 0, 0, 0, false);
            roundNote.SetActive(true);
            roundNoteText.text = healLine;
        }

        public void HideResult() => resultRow.SetActive(false);

        // True when the tallest strip no longer fits between the dice and the army bar (UI Scale 125%).
        public bool ShortCanvas => ((RectTransform)transform).rect.height - armyBarClearance - stripTop < stripTallest;

        private void LateUpdate() => PlaceStrip();

        // On a short canvas the strip hangs from its bottom edge above the army bar, so a row that appears grows it upward.
        private void PlaceStrip()
        {
            float canvasHeight = ((RectTransform)transform).rect.height;
            if (canvasHeight == placedCanvasHeight) return;
            placedCanvasHeight = canvasHeight;

            var stripRect = (RectTransform)strip.transform;
            bool shortCanvas = ShortCanvas;
            stripRect.pivot = new Vector2(0.5f, shortCanvas ? 0f : 1f);
            stripRect.anchoredPosition = new Vector2(0f, shortCanvas ? -shortStripBottom : -stripTop);
        }

        private void SetRing(Image ring, int result, Color? fixedHue = null)
        {
            ring.enabled = result != 0;
            // The glow keeps the alpha set on the prefab; only its hue follows the result.
            Color colour = fixedHue ?? (result > 0 ? Positive : Negative);
            colour.a = ring.color.a;
            ring.color = colour;
        }
        #endregion

        #region Fades
        private void StopAll()
        {
            if (swap != null) StopCoroutine(swap);
            swap = null;
            if (columnFades == null) return;
            for (int i = 0; i < columnFades.Length; i++)
            {
                if (columnFades[i] != null) StopCoroutine(columnFades[i]);
                columnFades[i] = null;
            }
        }

        private static void SetGroup(CanvasGroup group, float alpha, bool interactable)
        {
            group.alpha = alpha;
            group.interactable = interactable;
            group.blocksRaycasts = interactable;
        }

        private IEnumerator Swap()
        {
            card.alpha = 0f;
            yield return UIJuice.Open(strip, null, fadeSeconds, 0f);
            swap = null;
        }

        private IEnumerator Fade(CanvasGroup group, float target)
        {
            float start = group.alpha;
            for (float t = 0f; t < fadeSeconds; t += Time.unscaledDeltaTime)
            {
                group.alpha = Mathf.Lerp(start, target, t / fadeSeconds);
                yield return null;
            }
            group.alpha = target;
        }
        #endregion
    }
}
